### ISSUE TITLE
Allow for certain namespaces to be excluded from abandoned workload analysis

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1017]
Certain system namespaces exhibit abandoned workload characteristics but are obviously not abandoned.
Occurrences of abandoned workloads of this nature can be high, resulting in pages of relatively un-actionable recommendations.
Preferably, this would be configurable via config files.

gz#652

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-33) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
I totally understand this challenge. 

I believe this would be really hard if not impossible for many teams to manage in a helm values/config file. I actually think it could be better to read this context from Kubernetes. A pod/controller/namespace could be given the context of `expectedNetworkTraffic: low` via a Kubernetes label or annotation. This metadata would be useful for abandoned workloads but also many other things. 

Thoughts?

cc @nikovacevic @mbolt35 @michaelmdresser

**Comment by michaelmdresser** [comment]
I like the idea of putting a label or annotation on a K8s resource to help handle this problem because I think that it's safe to say that this is a general property of a K8s resource and so its reasonable for the property to be part of the resource itself. With that said, I'm a little wary about `low` and other qualitative values because it is ambiguous. I'd lean towards a boolean flag like `expectNetworkTraffic=false`, though that may lose the generality for non-abandoned workloads uses.

**Comment by nikovacevic** [comment]
Is there another general characteristic to these workloads? What are some examples?

**Comment by kirbsauce** [comment]
I believe etcd was the primary driver for this request.

**Comment by dwbrown2** [comment]
Another may be a batch job that does a bunch of work but has little to no network traffic.
