### ISSUE TITLE
Alert/Notification recipient identification via a label

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1030]
Currently, alert/notification recipients are identified in the UI or helm.  The ask is to have them also be identifiable via a label, as some partners leverage strict labeling during cluster deployment, therefore contact information is readily available and can often change.

gz#687

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-37) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
Thanks for reporting! We've discussed using the Owner label for this. Do we know current approaches being used to define?

**Comment by kirbsauce** [comment]
To define the recipient, one client is already capturing the email via a form with strict validation during cluster creation and annotating it.  In this case, the vision would be to identify the annotation to be used for alert/notification targeting.

**Comment by LaikaN57** [comment]
> Thanks for reporting! We've discussed using the Owner label for this. Do we know current approaches being used to define?

@dwbrown2 Lets make the label name configurable on the Kubecost side please. I find that hard-coding label names for configuration does not work well in the long-term due to unforeseeable collisions with other products or definitions.

As for our setup, we have a blessed git repo which installs a `namespace` for a newly defined "project". That repo requires you to specify a `namespace` and more/less a `pagerduty-endpoint`. You are then free to create anything you want in your namespace. We then have a combination of internal "app" helm charts and k8s policies that will then inject the `pagerduty-endpoint` into labels on anything you may deploy in your `namespace` such that downstream/sidecar monitors can properly route alerts (over-simplification here).

We can leverage a similar scheme with Kubecost where cost anomalies or reoccurring reports get sent to people based on a configurable label.

**A simple use case...**

I want to send a reoccurring report monthly to the team responsible for each `namespace` broken down by `deployment`. Each `namespace` is labeled with "kubecost_cost_owner".

So with a k8s structure like:
```yaml
Namespaces:
  frontend:
    Labels:
      kubecost_cost_owner: fe-cost@example.com
    Deployments:
      - web
      - mobile
  backend:
    Labels:
      kubecost_cost_owner: bob@example.com
    Deployments
      - databases
      - queues
```

We would expect a result like this:
- fe-cost@example.com would receive a report broken down, showing web and mobile totals
- bob@example.com would receive a report broken down, showing databases and queues totals
