### ISSUE TITLE
Ingress pathType implementationSpecific not working on EKS 1.21

### ISSUE THREAD

**Issue by windrammer** [kubecost/cost-analyzer-helm-chart#1063]
**Describe the bug**
When deploying the ingress object on EKS 1.21 it defaults to pathType implementationSpecific which causes issues when trying to browse the gui in a browser.

**To Reproduce**
Deploy chart to latest kubernetes with values ingess.enabled: true, a host set and TLS enabled.
Go to the hostname in a browser.

**Expected behavior**
The list of available clusters should populate and be available for inspection.

This behaviour can be fixed by setting the pathType to Prefix and should ideally be set as a configurable value or a set default depending on kubernetes version.

gz#772

**Comment by kbrwn** [comment]
hi @windramme We likely should add a pathType parameter to the ingress that is deployed by the cost-analyzer-helm-chart [here](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-ingress-template.yaml). For now as a workaround you may wish to use an existing ingress controller rather than the controller deployed by this chart.  We have an example of ALB Ingress that shows the usage of Prefix: https://github.com/kubecost/docs/blob/master/ingress-examples.md#alb-example

**Comment by windrammer** [comment]
Yes, thats pretty much what we ended up doing. Just wanted to give some feedback on the current experience of deploying the helm chart. Thanks for the response!

**Comment by keithhand** [comment]
Hello @windrammer, an update to the helm chart for versions 1.88.1+ resolves this issue. You can now customize this value by using the field `ingress.pathType`.

**Comment by keithhand** [comment]
Hi @windrammer, I just wanted to check in and see if customizing the field `ingress.pathType` on a later version worked for your deployment. If all is working, I can close this issue out. Or, if that solution didn't work, I'd be happy to help.

**Comment by windrammer** [comment]
This seems to fix it for us, this issue can be closed. Thank you.
