### ISSUE TITLE
Switch cluster view is confusing for federated users

### ISSUE THREAD

**Issue by kbrwn** [kubecost/cost-analyzer-helm-chart#1104]
**What problem are you trying to solve?**
Switch cluster view displays info about a single cluster. This under represents the data available for federated kubecost deployments and is confusing to endusers. (ie users think they are only looking at data for the cluster displayed)

**Describe the solution you'd like**

- option to disable switch view
- option to customize more than just cluster name 
- indication on switch view that federated / multi-cluster data is available 

gz#1344<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1344'>Zendesk ticket #1344</a>)</i>

**Comment by dwbrown2** [comment]
@nikovacevic and I have discussed this being "Switch context" or something related to be more clear.

**Comment by nealormsbee** [comment]
Adding this to my Coda for next week

**Comment by nealormsbee** [comment]
Submitted a draft POC here: https://github.com/kubecost/cost-analyzer-frontend/pull/462

Main idea is to prevent users from having to do work to set up and define a 'context' if they don't want to. They can still just add Kubecost cluster urls, but to help reduce confusion on multicluster setups, the UI would refer to these as "Kubecost Contexts", which is really what they are. Each cluster added is running an instance of Kubecost, which may be monitoring one or several clusters.

Send me your thoughts! If this seems directionally correct, I can do the same for non-react pages, the index page, etc.

**Comment by nealormsbee** [comment]
We've mostly talked about this in terms of the terminology (cluster vs. context) being confusing for federated users.

Another case that I imagine is common for federated users is that they don't have multiple contexts at all -- they want to use a single Kubecost context backed by a Thanos (or other) DB with _all_ of their cluster data. At that point, the terms aren't the problem. It's the idea of switching views at all that's confusing.

I'm not rushing to remove the `Switch Cluster/Context` button from the nav, but I can see how an index page with "List of Contexts!" is an annoying place to start each use when you will only ever have one context (that's why @valdisrigdon upvoted this, I believe).

What if we had a setting to make `/` redirect to `/overview.html` ?
Or we could do it automatically: If the FE detects that a KC is backed by Thanos, and only has one context configured, go straight to Overview?

**Comment by nealormsbee** [comment]
If I recall correctly, we've even talked previously about remove this view altogether, making Overview the landing page, and then leaving the nav bar's `Switch Cluster` option as the sole mode of switching.

**Comment by valdisrigdon** [comment]
+1 to the `overview` redirect if we are Thanos backed -- and if that's happening, the button near the bottom that says "switch cluster" could be hidden too.

**Comment by teevans** [comment]
> What if we had a setting to make `/` redirect to `/overview.html` ? Or we could do it automatically: If the FE detects that a KC is backed by Thanos, and only has one context configured, go straight to Overview?

@nealormsbee - Could I bother you to take point on doing this for 1.94?

**Comment by mbolt35** [comment]
I still feel like this idea bleeds over into all areas of the product and we should have a group discussion to nail this down completely. The opening "Select Cluster" is the misleading terminology. I _think_ this is what we're calling "Context" but it is truly a "Project" - the structure itself represents a single cluster or group of clusters. While we can't really do this today, I feel our data modeling and federation plans push us towards the direction of "Project Creation" where we allow a "New Project" modals that allow you to select specific clusters to include, etc... Again, not there yet, but I think we want to be open to this approach. 

The second part of this happens when you select a Project/Context, what does that actually mean? Today, it means that the handful of features that only work for the local install (omitting other cluster's data)... ie: Health, Some Savings features, and a few others... 

A good litmus for determining this is go to a page for a feature: Does it have a drop down selection for Cluster? If not, it is currently only showing you data for the local cluster. 

This is why it's confusing, because our main pages show you all multi-cluster data, allow you to filter clusters, include all of them, etc... However, there are a few features that still use local-only data. I have a proposal that would move the needle here in a big way by simply giving the frontend access to that "local cluster" data in a multi-cluster context. 

The Full Proposal: https://github.com/kubecost/kubecost-cost-model/wiki/Hosted-Multi-Cluster
Applicable to Frontend: https://github.com/kubecost/kubecost-cost-model/wiki/Hosted-Multi-Cluster#api-usage

While the title notes "Hosted Multicluster", this is very applicable for the on-prem install as well, especially for federated users.
