### ISSUE TITLE
Provide linkable results for Cost Savings/Request Sizing

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1113]
In an effort to provide focused direction to actionable items, we would like to ability to immediately provide customers with a view (link) of their namespace on a cluster when something of interest is identified.

**Comment by dwbrown2** [comment]
Kirby, can you share how this would differ from the current namespace page?

Webb
Kubecost, Co-founder

**Comment by kirbsauce** [comment]
I think the current namespace page would be fine, but as a more general solution getting a link to a report would be more versatile.  The ask is more about obtaining a link.  The user can't build a URL for a report as the filters are represented as some sort of hash.  @AjayTripathy, anything to add here?

**Comment by AjayTripathy** [comment]
From my notes on this conversation, I think this is more about request-sizing than it is about namespace.html, and more about making the request-sizing link human-readable. 

eg: http://nightly.kubecost.io:9090/request-sizing.html?filters=W3sidHlwZSI6Im5hbWVzcGFjZSIsInZhbHVlIjoia3ViZWNvc3QifV0%3D takes you to a page with the namespace filter applied, whereas we probably want this to be something like

http://nightly.kubecost.io:9090/request-sizing.html?filters=namespace:kubecost

**Comment by dwbrown2** [comment]
I believe @nealormsbee looked at these filters. Do you remember if there were reasons why human readable didn't work?

**Comment by nealormsbee** [comment]
I suspect human-readable URLs are achievable with some additional work. The current implementation was a more direct translation to the way we model filters on the request sizing page. It is an array of complex objects, so `encodeURIComponent(btoa(JSON.stringify(filters)))` was the simplest way to put `filters` in the URL in a reasonably condensed format, and making the URL more human-readable wasn't really a design consideration.

**Comment by nealormsbee** [comment]
Hi folks :wave: making an update.

I have a draft that improves things. The filters still aren't what I'd call "pretty", because the characters used to separate them get URI-encoded. But you can at least see what they are and make modifications to them in the URL if desired. That draft is here: https://github.com/kubecost/cost-analyzer-frontend/pull/461

And here's a screenshot showing the URL format:
<img width="1440" alt="Screen Shot 2022-01-04 at 2 16 59 PM" src="https://user-images.githubusercontent.com/981904/148112848-f4a6188d-226c-4276-837a-c144f626579a.png">

Thoughts?

The difficulty with using characters that *don't* get URI-encoded, such as `~` and `_` is that we would then need to either ban those characters from use in filter values, *or* come up with another method of escaping / encoding them when they are present in a filter value. That would entail writing some kind of encoding/decoding scheme of our own

**Comment by nealormsbee** [comment]
Fix is merged. I usually just close these on merge, but @kirbsauce is that preferable, or is it preferable to wait until the next release? This is done in the code, but users won't have it for another ~2 weeks. And we kind of use github for combination eng issue tracking _and_ feature request / user info etc. tracking

**Comment by nealormsbee** [comment]
Closing per guidance from Ajay :)
