### ISSUE TITLE
Configurable Overview Title

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1144]
**What problem are you trying to solve?**
In a federated environment, the overview title shows the name of the primary cluster.  This can be misleading if one feels it's seeing data only from the primary cluster but the total cost is of the entire environment.

**Describe the solution you'd like**
Option 1: make it configurable
Option 2: just have it say "Overview"
Option 3: remove it entirely

**Describe alternatives you've considered**
All options under solution

**How would users interact with this feature?**
Option 1 via settings or values.yaml
Option 2, 3 n/a

**Comment by dwbrown2** [comment]
@nealormsbee does this fit with the "switch context" change? Any updates on that one?

**Comment by nealormsbee** [comment]
It is definitely in the same class of UX problem. For this issue, I think an easy solution is not showing the active cluster name in the page title (just show "Overview"), which is the implementation here: https://github.com/kubecost/cost-analyzer-frontend/pull/434

So the overview redesign addresses this particular facet of the problem.

Re: progress on switch context. I have not done any work on it yet. I don't think changing the word "cluster" to "context" buys us much in the way of usability, because if all of the contexts have cluster names, then it looks like they are synonyms and it's still confusing. In a meeting, we briefly discussed something like showing a list of named contexts, where each context would list the clusters it contained. But again, I have not taken a crack at making that a reality.

**Comment by nealormsbee** [comment]
This is resolved in 1.89.0 -- the display will read `Overview / n clusters` where `n` is the number of clusters for which data is shown (always 1 for non-multicluster setups).

I still think the idea of a configurable title is interesting, and it might be good to show the name of the cluster in single-cluster setups, rather than `Overview / 1 cluster`.

Closing this issue for now, since multicluster users shouldn't be confused anymore.
