### ISSUE TITLE
ideally containers would specify resource limits

### ISSUE THREAD

**Issue by mdaniel** [kubecost/cost-analyzer-helm-chart#12]
As of this issue, none of the [`resources:` blocks](https://github.com/kubecost/cost-analyzer-helm-chart/blob/249ce8bd6bc795e5e17e583ad5af9f333f800f0e/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L86-L88) contain `limits:` clauses, meaning those containers can grow without bound

That's not an idea situation, and if the memory requests are only 55MB then setting a 256M upper bound seems like a perfectly reasonable starting point -- although the correct answer is influenced by observing the actual memory pressure of a running instance

**Comment by dwbrown2** [comment]
I agree we should add limits back to all of these containers.

For context, we removed because certain systems were being CPU throttled into oblivion during critical events, e.g. AWS billing data download. Like Matthew, I propose a set of conservative limits that can be lowered over time, maybe 256MB and 500M for cost-model?

**Comment by dwbrown2** [comment]
Fixed by #17
