### ISSUE TITLE
Network Cost Settings Configuration by GUI

### ISSUE THREAD

**Issue by despi89** [kubecost/cost-analyzer-helm-chart#1390]
**What problem are you trying to solve?**
Network Costs settings are currently configured in https://github.com/kubecost/cost-analyzer-helm-chart/blob/ab384e2eb027e74b2c3e61a7e1733ffa1718170e/cost-analyzer/values.yaml#L288-L322
While all other costs can be defined in the settings area of the GUI.

**Describe the solution you'd like**
Enable Network Costs definitions in the GUI settings area.

**Describe alternatives you've considered**
None

**How would users interact with this feature?**
GUI

gz#1728<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1728'>Zendesk ticket #1728</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-90) by [Unito](https://www.unito.io)

**Comment by mute-source** [comment]
Hi @despi89, 
I have the same "problem" and would also be happy if the costs could all be recorded and administered in the GUI.
Especially since this would also allow faster adjustments to be made by controllers who have less coding experience.
Cheers

**Comment by mbolt35** [comment]
I'm confused on what the request is here. The network-costs settings linked above aren't costs, they're specific classification options for IP/CIDRs. The costs for these classifications of traffic should be modifiable via the settings GUI, I agree. Especially because the actual costs values in helm are listed here:

https://github.com/kubecost/cost-analyzer-helm-chart/blob/3a429cbda4ffb8ca2681bdcc5f275d914506ac35/cost-analyzer/values.yaml#L712-L714

I'm still not sure if that's what is being asked, so some additional clarification would be awesome

**Comment by despi89** [comment]
Hi @mbolt35 
thanks for asking. I think it would be very helpful to have both, the classification as well as their costs to be configurable in the GUI. What do you think?

**Comment by mbolt35** [comment]
Updating settings on our frontend to include the costs should be relatively straight forward. However, for the classification settings, given that the network-costs pods exist as a daemonset, we would need to directly update a config-map, which I don't think we have permissions for. I'll need to look into this a bit more.
