### ISSUE TITLE
Can't view cost by annotation in Allocation UI

### ISSUE THREAD

**Issue by jcharcalla** [kubecost/cost-analyzer-helm-chart#1392]
**Describe the bug**

After enabling namespace [annotation emissions](https://guide.kubecost.com/hc/en-us/articles/4407595918231-Enabling-Annotation-Emission) with `--set kubecostMetrics.emitNamespaceAnnotations=true` it is implied  by "Owner Label / Annotation" and the description of it on the settings page that annotations can be used for label mapping (See screen shot below). However when Using an Annotation and aggregating by owner on the "Cost allocation" page, my annotated Namespace assets do not appear. 

Using a Namespace label does function correctly. Additionally I'm aware that aggregating by annotation currently only works via the [API](https://guide.kubecost.com/hc/en-us/articles/4407595916823-Allocation-API#querying). This makes me wonder if the description "Owner Label / Annotation -  Name of k8s label or annotation to designate owner/contact." on the settings page of the UI is correct.

**To Reproduce**
1. Enable annotation emissions. `--set kubecostMetrics.emitNamespaceAnnotations=true`
2. Add an annotation to a namespace. EX. `Annotations:  app.test.com/primary-owner: vader`
3. Set the "Owner Label / Annotation" field on the "settings" page to the namespace annotation. I tried both `app.test.com/primary-owner` and `app_test_com_primary_owner`
4. On the "costs allocation" page aggregate by "owner", at this point only `__idle__`  and `__unallocated__` appear.

**Expected behavior**
Annotations appear in the aggregated by owner view of the "cost allocation" page if that is the intended behavior.

**Screenshots**
Annotated namespace:
```
$ kubectl describe ns kube-system
Name:         kube-system
Labels:       kubernetes.io/metadata.name=kube-system
Annotations:  app.test.com/primary-owner: vader
Status:       Active
```

Settings page:
<img width="948" alt="Screen Shot 2022-04-26 at 3 58 38 PM" src="https://user-images.githubusercontent.com/17748044/165595753-0fd5da89-5af6-4a8f-835a-6a43091b9cfc.png">

Costs Allocation page with no results:
![Screen Shot 2022-04-27 at 2 37 24 PM](https://user-images.githubusercontent.com/17748044/165596378-209d035b-b616-4ca6-83a8-b2e31ca588e0.png)

**Comment by dwbrown2** [comment]
@jcharcalla I believe the Allocation page is WAI in the sense that aggregating by Annotation is just supported in the back APIs. I would for sure call the Settings description a bug though. 

Any chance you were able to confirm this was working for you in the underlying Allocation API? My proposal would be that we turn this into a feature request and bring the frontend UI to match the Settings description!

**Comment by AdamStack18** [comment]
@jcharcalla  Quick following up here.  Any chance you were able to confirm this was working for you in the underlying Allocation API?

**Comment by baldey-nz** [comment]
i have a similar situation here. Im using Kubecost v1.94.3 and as per https://guide.kubecost.com/hc/en-us/articles/4407595918231-Enabling-Annotation-Emission i have set emitPodAnnotations: true &  emitNamespaceAnnotations: true in my chart before deploying kubecost.
I have then annotated some pods with 'owner: test-owner' but i cant see the UI showing this cost allocated. I have also tried via the api using:
`curl https://myurl/model/allocation -d window=1d   -d aggregate=owner   -d accumulate=false   -d shareIdle=true   -G | jq .`
but i dont see the costs allocated, all i see is __unallocated__. 
If i add labels (instead of annotations) of 'owner: test-owner' then i see the cost allocated in both the api and the UI. 

It seems to me that the emitAnnotations functionality isnt working but i may be doing something wrong here, should i be creating a new issue for this? to me it seems related to this issue?

**Comment by baldey-nz** [comment]
Hi @AjayTripathy thanks for coming back to me. So i can see output for the pod based on my owner annotation if i query like this

curl https://myurl/model/allocation -d window=1d -d aggregate=annotation:owner -d accumulate=false -d shareIdle=true -G | jq .

is that what you mean?

**Comment by AjayTripathy** [comment]
Yep! In that case I think ti's just a matter of hooking up our predefined aggregations to our annotations. @Adam-Stack-PM let's make sure we get this tracked and added to the v1.96 release.
