### ISSUE TITLE
Asset drilldown with type filters already applied is odd

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#1404]
**Describe the bug**

**To Reproduce**
1. Apply a multiple filter to the assets page: http://34.69.101.254:9090/assets.html?agg=type&filters=W3sicHJvcGVydHkiOiJ0eXBlIiwidmFsdWUiOiJDbHVzdGVyTWFuYWdlbWVudCxEaXNrLExvYWRCYWxhbmNlcixOb2RlIn1d
2. Click on the node section to drill down
3. The data returned clears all filters/seems to return all assets 

**Expected behavior**
My guess is drilldown should be clearing all filters, since basically we're clicking on the node card and expect to see only nodes.

**Screenshots**
![Screen Shot 2022-05-04 at 1 54 22 AM](https://user-images.githubusercontent.com/453512/166650783-b8fc775b-97f5-4199-9368-20be0ea26339.png)
![Screen Shot 2022-05-04 at 1 54 16 AM](https://user-images.githubusercontent.com/453512/166650868-adeab27c-20d3-401d-a6ec-e8c6efec9f83.png)

Note how we are in the "node" drilldown section but have some filters applied, yet are seeing clustermanagement cost.

**Comment by AdamStack18** [comment]
@AjayTripathy  Was able to reproduce it. However, initially, it worked correctly.

@nealormsbee  mentioned we had something similar to this on the allocation page in the past that's been patched.

**Comment by nealormsbee** [comment]
I was not able to get this today and am out until the weekend. To help anyone who might pick this up:

This issue once exited on Cost Allocation as well. The problem is that we combine filters applied by Drilldown with user-applied filters, and filters of the same category are treated as unions. What happens is

```
Filter by type="ClusterManagement,LoadBalancer,Disk,Node"
Aggregate by Type
Drill down on one of the "Node" type row
The drilldown action applies a filter `type="Node"`
The resulting new filter is effectively `(type="ClusterManagement,LoadBalancer,Disk,Node") || (type="Node")
```

The solution implemented in Cost Allocation is to AND the drilldown-defined filters with the user-defined filters, resulting in the correct set of objects.
