### ISSUE TITLE
Unable to create a new recurring report alert on nightly

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#1468]
I am trying to create and test the following alert. When I click test alert, I get the following _unexpected_ error.... I'm guessing as a user that I need to save to test?

![](https://user-images.githubusercontent.com/298359/172756611-097c99ed-0419-44d1-b8c5-888a0f5364f0.png)

When I save, my email recipient is no longer there...

![](https://user-images.githubusercontent.com/298359/172756834-89393034-532f-4dad-a2cf-4761abd3ce7e.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-101) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
cc @teevans @AdamStack18 I'm guessing this existing in 1.94?

@kaelanspatel did you hit this in your testing of alerts?

**Comment by kaelanspatel** [comment]
@dwbrown2 I did test this, but it worked (and continues to work) for me. I'm guessing it's because there's no global value set? Tested this on the RC before the release, so I don't think any changes were made.
![image](https://user-images.githubusercontent.com/32113845/172932375-f8c2e06e-c6c3-426b-8366-6d2ff4f027f5.png)
![image](https://user-images.githubusercontent.com/32113845/172931218-1ba48e0b-fb37-483b-8068-66d2b0fb818a.png)

Also are we sure the email not showing back up (and maybe the test alert failure) isn't WAI? Did you press enter after adding the email? If so it should create a chip with your email in it which should persist. The "press enter" thing is IMO is not intuitive behavior admittedly....

**Comment by dwbrown2** [comment]
Wow, yes you are right. This is because I did not press enter. I may be a dense user, but I feel strongly that this isn't clear in our UI. 

cc @teevans great one for Anna's input!

**Comment by teevans** [comment]
@Annalillie - Take a look at this issue and see what you think. I'm thinking the tag style email input is probably good, but we adjust it to be an inline tag set, instead of having to hit the enter button. Thus, whenever a user clicks away, it automatically assumes it as a value. Similar to how gmail does their email addresses in their compose window.

**Comment by Annalillie** [comment]
@teevans This is very interesting. I think an input similar to gmail's in compose would be very useful here. There's also the possibility of shortening the "add recipients" field to make way for an "add" icon next to the input field.

**Comment by dwbrown2** [comment]
> @teevans This is very interesting. I think an input similar to gmail's in compose would be very useful here. There's also the possibility of shortening the "add recipients" field to make way for an "add" icon next to the input field.

I really like the same approach that gmail takes! i.e. if input loses focus then it attempts to add the email address. I believe it even shows as invalid if formatting doesn't match expectations?

**Comment by Annalillie** [comment]
I really like the idea of including an error state or microcopy if the formatting doesn't meet requirements. That way, there's no confusion on why the input wasn't accepted.

**Comment by LaikaN57** [comment]
I would add that, we should capture values not only on "click-away" events, but also on "form submit" events. I am likely to just throw in an email address and click submit instead of clicking in the "blank area" first.

**Comment by Adam-Stack-PM** [comment]
@LaikaN57, thanks for the input on this issue! 

@Annalillie, across several issues, I've noticed a great opportunity to improve how we handle form submissions, saving items, and user input. As we transition to the design system, would it make sense to create a standard treatment (failures/success/feedback) and map out where it should be applied?

**Comment by Annalillie** [comment]
That makes complete sense @Adam-Stack-PM. As we move forward, we will definitely find ways to improve our UX for input/form submissions as well as incorporating error state microcopy. This is something I am currently looking into.
