### ISSUE TITLE
Provide Release Notes file, or remove alpha/beta releases from the Release tab after the final version is released.

### ISSUE THREAD

**Issue by llamahunter** [kubecost/cost-analyzer-helm-chart#1473]
**What problem are you trying to solve?**
A clear and concise description of what has changed in each release.

**Describe the solution you'd like**
A Release Notes file, or no duplicate notes in the Releases tab due to internal alpha/beta versions, or both.

**Describe alternatives you've considered**
Downloading all the individual Release information from the Releases tab and manually editing out all the duplicate internal alpha/beta info

**How would users interact with this feature?**
They would read easy to digest release notes.

gz#1953<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1953'>Zendesk ticket #1953</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-103) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
+1, I think we can do better here. 

@llamahunter do you have a project that you think sets a good example? I've always thought that the Thanos team generally manages releases notes well: https://github.com/thanos-io/thanos/releases

**Comment by zorrobyte** [comment]
From my personal experience, comma.ai seems to do a good job with release management. 

They have a [master branch](https://github.com/commaai/openpilot) that they actively work on that contributors and testers can run and [provide feedback on](https://github.com/commaai/openpilot/issues). Once the release is considered stable enough, they update release notes and [publish a blog with changes](https://blog.comma.ai/0814release/). Finally, a [release branch is pushed to](https://github.com/commaai/openpilot/tree/release3), which stable users auto-update from.

Checking settings is also confusing as it claims the latest is 1.93.2  when the latest on the releases page is v1.94.1. It seems that whatever version is installed is "latest" even if not true:
<img width="264" alt="image" src="https://user-images.githubusercontent.com/7257172/173406043-42e763c2-916e-46b3-81f7-507054ab819c.png">
<img width="480" alt="image (1)" src="https://user-images.githubusercontent.com/7257172/173406067-9fae9c5f-646f-4a4a-951c-19c843003746.png">

If the UI doesn't have an interface element to perform an in-place upgrade, does it make sense to put a "latest" tag in the UI at all?

**Comment by teevans** [comment]
@zorrobyte - I found a goof on my end for the latest tag. I hadn't updated the OpenCost repository to have the latest releases. Only the helm chart, so that latest tag will update soon. Due to the rate limits around github's API, we cache the latest version for 24 hours, so customers should see that tag update by tomorrow night. 

Love the idea of more concise release notes. Also something like the image below could be neat. In-app notification showing the new functionality? 
![image](https://user-images.githubusercontent.com/3982846/173492886-b197f853-9687-4d6f-a66a-93cfc16a0f2f.png)

**Comment by AdamStack18** [comment]
@llamahunter Agree we can do better here. 

Before creating a solution, I want to ensure I understand your issue correctly. 

When we promote a release candidate to the official release (Example v1.93.0-RC.1 to v1.93), it is unclear what enhancements or fixed bugs after the release candidate was published? 

This is caused because I copy the RC release notes, add in fixed bugs then publish the notes with the official release.  Is this correct?
