### ISSUE TITLE
1-click Sizing Does not work if there Autoinjection of Containers

### ISSUE THREAD

**Issue by svelango** [kubecost/cost-analyzer-helm-chart#1476]
**Describe the bug**
When 1-click is run on pods having Istio Service Mesh it gives error "update struct based on plan: container 'istio-proxy' not found in controller spec"

**To Reproduce**

1. Install Istio
1. Kubecost Version v1.93.1
1. Run 1 Click Rizer

**Expected behavior**
1 Click Updating Deployments according to recommendation

**Screenshots**
![Test](https://user-images.githubusercontent.com/741834/173398276-d5cfc24a-1157-4785-9dd9-a3249b58f41e.jpg)

gz#1961<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1961'>Zendesk ticket #1961</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-104) by [Unito](https://www.unito.io)

**Comment by jcharcalla** [comment]
@svelango Thank you for reporting this. To help us reproduce this can you tell us if you are you using the Automatic (via the mutating webhook) or Manual sidecar injection for Istio?

https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/

**Comment by svelango** [comment]
Thanks for checking. We are using mutating webhook.

**Comment by kirbsauce** [comment]
@nealormsbee , not likely your area of the code but wondering if you could direct this to the right person for triage?

**Comment by nealormsbee** [comment]
Can do. I'm going to guess @michaelmdresser is the right person to triage -- he's done a lot of work on one-click request sizing.

**Comment by nealormsbee** [comment]
Thank you Michael! Surfacing some info for @svelango here since the other issue is private.

We have reason to suspect that our cluster-sizing recommendations cannot, currently, accommodate Istio's automatic sidecar injection, because those containers are not present in the K8s resource spec. The other containers should still rightsize correctly.

It will require product work

- To better-convey that there was only a partial failure
- To document scenarios that are not fully supported by one-cick rightsizing (such as Istio's automatic sidecar injection)
- To possibly accommodate these scenarios

There is unlikely to be a great workaround in the meantime, apart from not knowing that other containers will size correctly and ignoring the error. Please note that this is considered a `beta` feature and we do expect to run into some situations like this one.

I don't want to promise that this partial-error-reporting UX will be improved in our next release (v1.96), but a general UI/UX overhaul is a major part of our near-term roadmap, and this UX would fall neatly into that category. So you can expect improvements here relatively soon

Cheers and thanks for the report 🎷

**Comment by jcharcalla** [comment]
@Adam-Stack-PM I've had a customer ask for an ETA on this, can you provide one?

**Comment by Adam-Stack-PM** [comment]
@jcharcalla, Thanks for the follow-up. 

This is marked as P2. This means we will likely be fixing this issue as part of a larger initiative around error handling or rightsizing down the road (I don't have a date yet).

My understanding is this is currently working; however, it is 100% a poor user experience that we need to improve.  If this is not the case, let's elevate the priority.

**Comment by jcharcalla** [comment]
Thank you, I will follow up with them to see if they are able to make use of it.
