### ISSUE TITLE
enhancements to overview-new.html

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#1499]
Note: I'm happy to break this up into multiple requests, just let me know. Sorry if there are duplicates to other requests.

**What problem are you trying to solve?**

Enhance overview-new.html. Just some ideas- I really do love the new page!

**Describe the solution you'd like**

Couple ideas for the overview-new.html page:

1. [x] Remove _idle_ from cluster breakdown.
2. [ ] Link "Cluster Breakdown" to allocations.html?idle=shareByCluster&agg=cluster
3. [ ] Link "Cluster Trends" to allocations.html?idle=separate&agg=cluster&chartDisplay=series&window=14d
4. [ ] Link "Namespace Breakdown" to allocations.html?idle=shareByNode&agg=namespace
5. [ ] Link "Namespace Trends" to allocations.html?idle=separate&agg=namespace&chartDisplay=series&window=14d
6. [x] In "Cluster Breakdown" Change link when clicking a cluster to idle=separate
7. [ ] (if easy) In Namespace Breakdown add number of clusters column
8. [ ] (if easy) In Cluster Trends chart dropdown: add Idle Costs
9. [x] On Cluster Trends chart dropdown: change Nodes to: # of Nodes
10. [x] On Cluster trends chart dropdown: change Pods to: # of Pods
11. [x] On Namespace trends chart dropdown: change Clusters to: # of Namespaces
12. [x] On Namespace trends chart dropdown: change Pods to: # of Pods

Clearly you can add "if easy" to all of them.  I was just highlighted ones where it seems more difficult than the others.

**Describe alternatives you've considered**

N/A

**How would users interact with this feature?**

Via the UI.

**Comment by teevans** [comment]
Love this - Thank you sir!

**Comment by AdamStack18** [comment]
@teevans any specific items  on this list we want to tackle in an up coming release?

@jessegoodier  Is this in order of priority or could you separate into two categories? 

Example 
1. Feel strongly about
2. Nice to have/ would be neat

**Comment by dwbrown2** [comment]
> Remove idle from cluster breakdown.

+1, thought Neal did this actually

> Link "Cluster Breakdown" to allocations.html?idle=shareByCluster&agg=cluster

Is this when you click an individual row? If so, would it just show one line-item? One alternative would be to link to Assets by cluster. e.g. http://nightly.kubecost.io:9090/assets.html?agg=type&context=W3sicHJvcGVydHkiOiJTZXJ2aWNlIiwidmFsdWUiOiJLdWJlcm5ldGVzIiwibmFtZSI6Ikt1YmVybmV0ZXMifV0%3D

> Link "Cluster Trends" to allocations.html?idle=separate&agg=cluster&chartDisplay=series&window=14d

Would this be making the bars links or something else? 

<img width="750" alt="image" src="https://user-images.githubusercontent.com/298359/176339934-4bef9501-0b33-490f-b0f3-87907f6f698c.png">

**Comment by jessegoodier** [comment]
looks like it is still there: http://nightly.kubecost.io:9090/overview-new.html

**Comment by kc-adawson** [comment]
Is overview-new set to be promoted in 1.96? If not, can we give the users an ability to "opt into the new overview"? I think the overview-new even in its current state is much better than the old overview:

<img width="1440" alt="2022-07-21_18-58-11" src="https://user-images.githubusercontent.com/101200254/180329309-58a305e6-d164-4c09-8554-7a25c41932e0.png">

**Comment by dwbrown2** [comment]
@nealormsbee has a big PR in the works for performance! I think it's still part of 1.96 plan but he'll know best.

**Comment by nealormsbee** [comment]
Yes! The plan is to promote overview-new to overview as part of 1.96. Performance is improved to the point that the page loads scale cluster data on the order of 10~20 seconds. I need to confirm that all numbers are solid (it seems like efficiency calculation may have been messed up in the translation) but otherwise we're looking good here.

**Comment by nealormsbee** [comment]
Revisiting to add some additional clarification.

- The plan is to promote new overview to the default experience in 1.96
- It will likely, for large scale users, load somewhat more slowly than the current overview, because it includes pod-level metrics. However, it is still loading data fro the scale cluster in <20s and there is likely room for more improvement.
- @jessegoodier idle costs will be removed from cluster breakdown when my performance enhancements PR goes in! I like all items listed, and they should be straightforward with the exception of #8. I'm currently having the backend do idle-sharing for us, so splitting it out would require some refactoring that I'd rather save for the future.
- @dwbrown2 I took numbers 2-5 to mean adding links to the card footers, like the current overview has. Correct me if I'm mistaken, @jessegoodier

Thanks y'all! It bears repeating that this kind of feedback and product engagement is *really* valuable, since you're basically our most accessible power-users :)

**Comment by nealormsbee** [comment]
I changed the list in OP to have checkboxes so I can check things off as I work.

I guess number 7 is also an interesting one, because that table currently treats cluster/namespace pairs as unique items (hence the 'cluster' column). So if you have a namespace duplicated across 3 clusters, it would show as 3 different items. I think it would be confusing to include "cluster" and "cluster count" columns together. Do you think that table is more useful with each item treated as the aggregation of a namespace across all clusters?

**Comment by nealormsbee** [comment]
Sorry for the quadruple post! One more thing. A link to the updated Overview in progress is here: https://kc-frontend-dsx10b8n7-kubecost.vercel.app/overview-new?backends=https%3A%2F%2Fmulti.test.kubecost.io

I'm working through these UI enhancements, and also doing my best to test out different cases for numerical accuracy. I'm seeing some small numerical discrepancies that I'm trying to track down. @jessegoodier and/or @dwbrown2 it would be a big help if you have a little free time to click things and point out issues where things don't match, either here or on the PR https://github.com/kubecost/cost-analyzer-frontend/pull/794

I also want to make the loading state of the page a bit nicer. It takes about 20s for this page to load on the scale cluster.

**Comment by srpomeroy** [comment]
What aggregation is the cluster efficiency metric based on? It used to be namespaces in the old overview. Is it now cluster? We should call out what the aggregation is.

**Comment by srpomeroy** [comment]
Have we explored using line charts instead of stacked bars? Would be much easier to see the rate of change for a particular resource of time compared to stacked bars.

**Comment by jessegoodier** [comment]
This looks great! I'll try out and let you know if I find anything.

**Comment by dwbrown2** [comment]
Looking awesome @nealormsbee!

* Just curious, how much does dropping pod data impact load time on scale cluster? Would love to see if we can get that down.  
* What do you think about deep linking this card to spend aggregated by Service with cloud filter? Currently just shows one-line of "Cloud" 
<img width="259" alt="image" src="https://user-images.githubusercontent.com/298359/180515723-5b7b0c69-687b-42c3-8a85-c0a0eeb9ba0f.png">

* High row counts feels like it makes these cards have excessive vertical size. Thoughts on dropping count per page drop down or doing scroll on this view like in the new design system? I'd call this P2 at best. 
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/298359/180516057-948b183e-2f26-4626-9e55-d806b1edd730.png">

**Comment by jessegoodier** [comment]
I think this should be #of namespaces?
![image](https://user-images.githubusercontent.com/31039225/180517261-0b0eb7c9-bd21-477c-9657-062cbaf0515e.png)

**Comment by kc-adawson** [comment]
It would also be great if we had ability to create a "friendly name" for Cloud Accounts, alongside the "account-id". It's tough to tell what is what with the number as the only an identifier. 

<img width="1261" alt="2022-07-22_16-05-44" src="https://user-images.githubusercontent.com/101200254/180519095-8d8df538-3b5d-4457-8be0-bcb3a4816e95.png">

**Comment by kc-adawson** [comment]
Also on 1.95.0, seeing blank links on multiple different Kubecost deployments. You can see it does this on both the Cluster and the Namespace sub-modals on 2 different instances (demo.kubecost.xyz and nightly.kubecost.io)

![Kapture 2022-07-22 at 16 09 21](https://user-images.githubusercontent.com/101200254/180519507-62f8076b-d7da-470d-8f2c-76cf762800ae.gif)

**Comment by srpomeroy** [comment]
> It would also be great if we had ability to create a "friendly name" for Cloud Accounts, alongside the "account-id". It's tough to tell what is what with the number as the only an identifier.

We could pull this data from the bill/api where available as opposed to having to maintain a config-map or some other data source.

**Comment by nealormsbee** [comment]
@srpomeroy 
>What aggregation is the cluster efficiency metric based on? It used to be namespaces in the old overview. Is it now cluster? We should call out what the aggregation is.

The query is aggregated by `cluster,namespace`, but if I'm generating that final number correctly, I don't think it should matter. It should be the average request/usage efficiency of all allocations in ETL, with `__idle__` factored in.

>Have we explored using line charts instead of stacked bars? Would be much easier to see the rate of change for a particular resource over time compared to stacked bars.

I'm down to visit different visualization options! Probably not this release because there's polish left to do on this page, and I have additional items that need to be done next week.

@dwbrown2

>Just curious, how much does dropping pod data impact load time on scale cluster? Would love to see if we can get that down.

That speeds things up *dramatically* due to the dimensions of scale cluster data. If we drop pod-level info altogether, we're dealing with `cluster/node/namespace`. There are only 30~40 unique namespaces per day, so we go from working with ~120k items per day (pods) to ~35 items per day.

>What do you think about deep linking this card to spend aggregated by Service with cloud filter? Currently just shows one-line of "Cloud"

That seems reasonable to me :joy:

>High row counts feels like it makes these cards have excessive vertical size. Thoughts on dropping count per page drop down or doing scroll on this view like in the new design system? I'd call this P2 at best.

I can make that 5 rows per page in less time than it took to type this sentence.

@jessegoodier

>I think this should be #of namespaces?

It's intended to be # of clusters! That mode is supposed to show the number of clusters in which each namespace exists, on each day. Sort of the opposite of the table situation I mentioned above, where each row is a `cluster/namespace` pair, if that makes sense.

I get how it's confusing...in the table we treat a namespace as "belonging to a cluster" (one-many) and then in the graph we treat it as a many-many type of relationship. I'm not really sure what the right resolution here is.

@kc-adawson 

>It would also be great if we had ability to create a "friendly name" for Cloud Accounts, alongside the "account-id". It's tough to tell what is what with the number as the only an identifier

I like that idea. Was going to suggest a Helm config until I saw Sean's comment. Won't make 1.96 and will likely entail some UI/API cooperation. Would you mind opening a separate enhancement issue for this?

>Also on 1.95.0, seeing blank links on multiple different Kubecost deployments. You can see it does this on both the Cluster and the Namespace sub-modals on 2 different instances (demo.kubecost.xyz and nightly.kubecost.io)

Good catch. Those links are fixed in my open PR for this view! So it won't be a problem when we promote in 1.96.


@all HUGE thank you for taking the time.

**Comment by jessegoodier** [comment]
Should we close this? 

It is mostly done and we can create a new ER for anything that comes up again?

**Comment by nealormsbee** [comment]
That sounds good to me. With the different design, several of these may not even make sense now. Closing the issue. Thanks Jesse!
