### ISSUE TITLE
Switch to human readable parameters in URL instead of Base64 encoded 

### ISSUE THREAD

**Issue by zorrobyte** [kubecost/cost-analyzer-helm-chart#1501]
**What problem are you trying to solve?**
Given a URL such as
```allocations.html?title=Cumulative+cost+for+last+7+days+by+namespace+%2B+controller&window=7d&agg=pod&chartDisplay=series&idle=separate&rate=cumulative&filters=W3sicHJvcGVydHkiOiJwb2QiLCJ2YWx1ZSI6ImsqIn1d&context=W10%3D```

`filters=W3sicHJvcGVydHkiOiJwb2QiLCJ2YWx1ZSI6ImsqIn1d`
==
`[{"property":"pod","value":"k*"}]`

**Describe the solution you'd like**
Customers would like to programmatically generate view URLs. Such can be difficult as we base64 encode them.

**Describe alternatives you've considered**
We could document on how to use Base64.

**How would users interact with this feature?**
Self explanatory

gz#2055<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2055'>Zendesk ticket #2055</a>)</i>

**Comment by teevans** [comment]
So. Couple of thoughts here. 

1. The reason this exists is because of the limitation of the browser URL. Either we encode to base64, or we attempt to encode every possible character into a browser string. Candidly, I can't stand either of these approaches because the browser string is really not meant to do things like this. 
2. Generating programmatically is already possible, I would suggest we go with your alternative solution of documenting how we use base64 as this is something that would invalidate all prior URLs that customers have used in the past.

**Comment by zorrobyte** [comment]
The customer is satisfied with using Base64. This can be a documentation addition in the future.

Thanks for the help!
