### ISSUE TITLE
Ensure all namespaced resources have namespaces available.

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#1527]
**Describe the bug**
Some of the namespaced resources for dependent charts – Grafana/Prometheus are missing namespace values. So unless the namespace is explicitly specified (ie kubectl apply -f … -n <Namespace> ) these are  installed in default namespace.

**To Reproduce**
kubectl apply -f <templates>

**Expected behavior**
Specifying namespace implicitly via Values is supported.

**Comment by linhlam-kc** [comment]
I'm contacting and scheduling a call with partner in the week of July 11st for learning more about the bug and their expectation.

**Comment by linhlam-kc** [comment]
I had a phone call with partner on Jul-14. The issue happened because of their internal system does not use Helm or Kubectl to deploy Kubecost but using their in-house tool to call K8s API without overriding namespace feature. Their ask is to update all of our resources templates in all of the helm charts and subcharts in consistent format with namespace is explicitly specified. In the meantime, partner is exploring possible solutions to support our Helm charts as is so it is not blocking them.

Action items:
- Pending partner to update the fix from their end.
- Pending partner to send the list of resources template that need to be updated from their testing.
- If the fix from partner side doesn't work, we need to update all of template resources metadata to specify namespace using release name or via Values. Example logic:

```
{{- if .Values.namespaceOverride -}}
{{- .Values.namespaceOverride -}}
{{- else -}}
{{- .Release.Namespace -}}
{{- end -}}
```

**Comment by linhlam-kc** [comment]
@Adam-Stack-PM : Partner updated that they have solution to fix it on their end. So item 3 is not required now. However, in the long term, we need to standardize namespace name to support some CI/CD tool like Circle CI.

**Comment by Adam-Stack-PM** [comment]
@linhlam-kc, Thanks for the update. Could you close this issue out and open a new issue to support additional CI/CD tools? Ideally, this would include a list of a few popular tools. 

 If you could label it enhancement + CI/CD  tit will help keep this on our radar.

**Comment by linhlam-kc** [comment]
@Adam-Stack-PM Yup, I will close this one and open new enhancement issue.
