### ISSUE TITLE
Efficiency flips when changing Idle Allocations

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#1600]
**Describe the bug**

https://user-images.githubusercontent.com/453512/182208507-5a2f0b01-8f4b-4e51-8c9b-69c420d924d3.mp4

**To Reproduce**
See above video

**Expected behavior**
Idle allocation should not impact efficiency-- it should be calculated before Idle is applied.

**Comment by nealormsbee** [comment]
Info on how these efficiency numbers are calculated:


## Frontend
Most efficiency calculation for allocations takes place on the frontend. The Summary API sends request/usage averages for CPU and RAM, and start/end timestamps for the allocation. From this, the frontend determines the cpuEfficiency and ramEfficiency, and takes a cost-weighted average of those values to get the allocation's total efficiency.

The frontend is definitely taking `__idle__` into account today. This has been the source of a *ton* of confusion from users and devs alike, because when `__idle__` is *included* in the calculation, we're effectively talking about *hardware efficiency*, and when `__idle__` is *hidden*, we're talking about usage/request efficiency. Since `__idle__` has a request/usage of `0`, its `request/usage` efficiency is technically undefined, but we set it to `0` and use the `__idle__` cost to cost-weight this 0-efficiency thing into the total calculation.

I am *all for* changing the efficiency calculations to ignore idle entirely. It will simplify a lot of special-case code dealing with `__idle__`, and probably be less confusing for users, ultimately. I also think we should be very careful with this decision. It basically redefines what "efficiency with separate idle" means for this page, and that definition has been around for at least the last 18 months.


## Backend
We may want backend adjustments around how idle sharing works, in order to keep efficiency numbers consistent. My knowledge is less robust here, but I *believe* that when we share idle by node or by cluster, we are spreading idle *costs* across allocations without altering their request and usage values. An Allocation's `totalEfficiency` is a cost-weighted average of its cpu efficiency and ram efficiency. So, when sharing idle, the cpuEfficiency and ramEfficiency of an item should stay the same. However, if the Idle costs being shared *change the ratio* of `cpuCost:ramCost` for that item, then the *total efficiency* for that item will change as well (because the weight given to each efficiency subtype will change).

**Comment by AjayTripathy** [comment]
Hey @nealormsbee thanks for that. Let's clarify the purpose of efficency and work backwards from there: it's used to define what workloads need to be prioritized at for right-sizing. Since you can't actually control machine efficiency (idle) by making those adjustments directly, I feel like idle should be entirely removed from this calculation*.

My proposal is the following-- let's start with the frontend change ignoring and see if that gets the numbers to stay fixed as idle is applied or unapplied. We can assign someone from the backend to second half of this issue but hold off on it. What do you think?
                          

*Actually the paradox is on fixed infrastructure as you increase efficiency idle goes _up_!

**Comment by nealormsbee** [comment]
That rationale totally makes sense to me, and so does the plan of action.

I like the idea of Cost Allocation focusing on "Workload Land" so that rightsizing workloads has an immediate observable impact on your total efficiency number. And then maybe it makes sense to add a "hardware efficiency" column in the Assets page? I think this'll clear up a lot of existing confusion around efficiency.

--
Discussed briefly out of band, but I'll summarize here: the Allocation page has done efficiency this way for quite a long time, so I think that if we make this change, we need to communicate it very clearly and loudly if we want to avoid a rash of user confusion.

If we can take care of that, then 💯 🔥 👍 🚀 
I'll draft a branch with the frontend updates.

**Comment by michaelmdresser** [comment]
Thanks for the clean explanations Neal, as always. The backend is definitely a bit thorny when it comes to efficiency because after idle is shared to an `Allocation` (in the regular Allocation API, in-Go and in the HTTP endpoint) you lose the context needed to calculate efficiency "correctly" as you're doing in your FE PR. Worth a look at some point, but all progress is good progress.

> *Actually the paradox is on fixed infrastructure as you increase efficiency idle goes up!

I've always found this interesting. In the way I think about efficiency, its more like this: as you increase workload efficiency (via request sizing) _"cluster efficiency"_ (the thing cluster sizing optimizes) goes down, which corresponds to increasing idle. My suspicion is that these two kinds of efficiency and how they influence one another are a major source of confusion.

**Comment by Adam-Stack-PM** [comment]
@michaelmdresser,  Are we good to close out this issue related to the bug fix or more work before we close? 
If the backend work is not urgent, can we open a new PR to consider for a later release?

**Comment by michaelmdresser** [comment]
This is fine to close now that Neal's PR is merged.
