### ISSUE TITLE
Add "Current/Now" Window in Container Rightsizing

### ISSUE THREAD

**Issue by kc-adawson** [kubecost/cost-analyzer-helm-chart#1611]
**What problem are you trying to solve?**

The smallest time window available for container rightsizing is 2 days. If someone is actively rightsizing workloads and checking back into Kubecost, the 2 day window seems to contain the old resource settings in its analysis. 

I resized my clusters with Kubecost yesterday, and now I want to check on how everything looks. I select 2 day window:

![](https://user-images.githubusercontent.com/101200254/183294152-d1c9fb85-74e3-4af5-8441-53a10d192f9b.png)

I notice the container with the largest savings is one that I already resized yesterday. It shows me that the requests are 200m, which I thought I had already resized down to 10m.

![](https://user-images.githubusercontent.com/101200254/183294158-a939ddad-7dfa-47ea-a0b2-6c010c98fb15.png)

When I click into that container, it seems to have held on to the historical request settings before and after I resized, and is showing the 200m even though my container is currently set to 10m.

![](https://user-images.githubusercontent.com/101200254/183294187-135fe328-d6d5-4f68-b149-471db91d1be0.png)

**Describe the solution you'd like**

If we had a new "Current" window that factored in only the last detected resource settings over the last few hours (2 hours/4 hours?) it would allow for more "instant gratification" while actively rightsizing, instead of waiting 2 days for the old config history to purge out. It also helps Kubecost because more of a realtime asset for teams doing this work.

**Describe alternatives you've considered**

If adding a new time Window is overkill, we could adjust the UI so that it always points out to users what the more recently detected resource settings are, so people don't get confused and think their changes were not applied.

**How would users interact with this feature?**

Via the same "Window" dropdown we use today, as a new option for "Current".

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-148) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
The main reason we did this was to indicate users shouldn't be making critical right-sizing decisions based on really small time windows. But I definitely see your points. I see two independent ones:

1) we should be using the latest/current request. I may even call this behavior a bug. 

2) we can support more flexible window options here. @teevans think we should bring full window support of assets/allocation here? We'd still need last several hours options but that would give users lots more flexibility.

**Comment by michaelmdresser** [comment]
I'd call this a product-level bug -- we should be showing the latest-known request for "Current Request", rather than the average over the window (which is what we're currently showing). I think this is achievable at the API level right now with a bit of eng work.

If we do that, we can continue using the regular set of windows for calculating recommended requests, because that only takes into account usage data.

**Comment by nikovacevic** [comment]
I agree that we should prioritize the ability to see something like "last known request" -- even though we'll never be able to do "current," per se, because that can change faster than ETL can possibly pick up the change.

But I think we need to be very careful that we don't let users easily view and act on _recommendations_ generated from a too-short window. Like... even 2 days is arguably a dangerously low setting. It just happens to be efficient.

**Comment by kc-adawson** [comment]
I understand the time window concerns - If we can do the "Last Known Request" like you said, I think that would solve the issue and improve the experience.

**Comment by dwbrown2** [comment]
I agree with Michael, I recommend we just show latest measured request in the UI/table and maybe provide a tooltip to indicate it's the last measured.

**Comment by michaelmdresser** [comment]
Since we're aligned on showing the latest-known request, I have a followup question: **should we only show recommendations for workloads that, as far as we can tell, are "live"?**

Live could mean: shows up in the most recent filled AllocationSet, has an End matching the End of the last full (has at least one Allocation whose End matches the End of the Set, if this is possible to check -- I know it is for SummaryAllocationSet) AllocationSet, or perhaps something else.

For example, say we have a unique cluster/namespace/controller/container (important: ignoring pod) in our Allocation data. If that workload is "live" we would show a recommendation because a modification would actually impact cluster resource allocation. If it isn't "live", making a modification would have no impact because the workload doesn't exist any more.

This gets a little convoluted with our concept of savings here, because we take a "your past savings for the query window would have been X if you applied these recommendations instead of the request we measured" approach and scale that to a monthly rate. If we cut out non-"live" workloads, it becomes "your _past_ savings for the query window for _currently running_ workloads would have been X if you applied these recommendations instead of the request we measured".

This could even be a flag, like `liveWorkloadsOnly=true`.

**Comment by michaelmdresser** [comment]
V2 recommendation API PR, which is up now [1] includes logic to calculate the "current" request for each request sizing recommendation. Some UI changes will have to be made for the new API, so this functionality will not be available in the UI immediately. Progress is being made, though!

I have _extremely_ rough UI proposal for the new API [2] if anyone would like to provide feedback.

We can leave my above question to the UI, I think -- the UI can just filter out recommendations with `null` current/latest request information if the behavior is desired.

[1] https://github.com/kubecost/kubecost-cost-model/pull/923
[2] https://docs.google.com/document/d/1_UaZH8NQFmZph8KYVtlqo72AliJNpu6ve6i7Y-ZPcnU/edit

**Comment by michaelmdresser** [comment]
Issue for tracking UI work that will get "current" request info on this page, as requested: https://github.com/kubecost/cost-analyzer-frontend/issues/1018

**Comment by michaelmdresser** [comment]
Please note that "current" as far as the new API is concerned is the most recent ETL window. So this will lag as much as the latest ETL window lags (1h normally, possibly 4h with Thanos?).

**Comment by dwbrown2** [comment]
> 1h normally

Is this the expected case in a standard deployment? I thought ETL rebuilt every ~10 minutes

**Comment by michaelmdresser** [comment]
Apologies, yes I think you're right there. So a lag of <=10m normally and <=3h 10m if it's Thanos (and if I remember Thanos data lag correctly...).

**Comment by michaelmdresser** [comment]
Actually, it's a little more complicated than that because we average request over an ETL window. So the _exactly_ correct request can lag as long as 1h/4h.
