### ISSUE TITLE
_Monitor Kubecost Health_ in Alerts shows disabled even after entering all required details and clicking save button

### ISSUE THREAD

**Issue by praveenkumar0566** [kubecost/cost-analyzer-helm-chart#1648]
**Describe the bug**
The toggle button in _Monitor Kubecost Health_ in Alerts gets enabled only if values 7d or 10m are entered in the "window" section, Any other value entered for the first time and saved the button remains grayed out.

![image (4)](https://user-images.githubusercontent.com/102574445/185684870-4d7c9e27-d389-4e8e-abec-80960e623272.png)

**Observation:**
As a workaround to make it work with any other value apart from 7d or 10m, the user needs to first enter 7d or 10m in the "window" save it until the button gets enabled then click on edit to enter any desired value in window save it, the _Monitor Kubecost Health_ get enabled 
**To Reproduce**

1. Go to 'Alert'
1. Click on 'Monitor Kubecost Health'
1. Enter any value apart from 7d and 10m in the "window"
1. Click on the save button
1. button doesn't get enabled

**Expected behavior**
The toggle button should get enabled after clicking the save button
![image (4)](https://user-images.githubusercontent.com/102574445/185686211-5ce38ff0-a792-467a-ade4-211c3ddcc3c4.png)

**Screenshots**
![image (6)](https://user-images.githubusercontent.com/102574445/185686371-389ef27a-3da1-4055-ac66-3429c74ad330.png)
![image (5)](https://user-images.githubusercontent.com/102574445/185686421-43042e37-1932-4cf4-a861-8b2e2fc567d2.png)

gz#2444<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2444'>Zendesk ticket #2444</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-158) by [Unito](https://www.unito.io)

**Comment by nealormsbee** [comment]
I'm seeing odd behavior with this feature, but not quite as described in the issue OP. Will enumerate differences here to make sure I'm not missing anything:

1. I think "Monitor Cluster Health" is the alert in question, not "Monitor Kubecost Health", because the Kubecost Health alert does not accept a Window field.
2. Valid relative windows other than "7d" and "10m", such as "6d", do work. What does not work are invalid relative windows such as "0" (pictured in the submitted screenshot).
3. The workaround does not work for me. If I create a health alert with a valid window (e.g. "7d"), and then use the Edit button to change the window to e.g. "0", and save, the switch goes back to gray. What's happening behind the scenes is that the server is seeing an invalid alert configuration, discarding it, but still replying with a "200 OK" response. The UI re-fetches the list of all alerts, which no longer includes a cluster health alert (because it was discarded), and moves the switch to "off".

Based on these, I'd vote to mark this as P2, because the feature is working correctly. The problem is that we don't validate the form ahead of time, or show appropriate error feedback when the user submits an invalid alert config. Steps to improve the experience here would be to:

1. Add form validation and prevent submission of invalid data
2. Have the server reply with an appropriate "400 Bad Request" response if an invalid payload is submitted
3. Have the UI relay error responses to the user
