### ISSUE TITLE
Endpoint requestSizing with specified time ranges

### ISSUE THREAD

**Issue by guijusto90** [kubecost/cost-analyzer-helm-chart#1714]
**What problem are you trying to solve?**

We would like to know the efficiency/saving and recommendations of applications at specific times, eg 12:00-15:00. Today we can specify ranges like this only on the allocations endpoint. When we query this specified time, we get error 500.

**Describe the solution you'd like**
To query the endpoint model/savings/requestSizing with specified widow, eg "window=2022-09-25T12:00:00Z,2022-09-25T15:00:00Z"

**Describe alternatives you've considered**
Query on endpoint /allocations, but doenst show like model/savings/requestSizing

**How would users interact with this feature?**

Yes, they could have more specific filters in the interface.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-184) by [Unito](https://www.unito.io)

**Comment by felipegimenez** [comment]
This feature will be very util for us. Because in endpoint "/allocation" don't have target and savings parameters.

**Comment by Adam-Stack-PM** [comment]
Hi @guijusto90, Thanks for the idea.  @felipegimenez for the additional upvote. Will review with the engineering team and consider it for an upcoming release. 

CC: @michaelmdresser, I Wanted to get this on your radar.

**Comment by michaelmdresser** [comment]
Hi @guijusto90! For a variety of reasons, our request sizing APIs only support querying specific windows if they are multiples of 24 hours and are aligned to UTC 00:00. This means that you won't be able to get recommendations based on data from windows smaller than 24 hours.

Working with what you've provided, `window=2022-09-25T12:00:00Z,2022-09-25T15:00:00Z` won't give you any data from the request sizing API, but `window=2022-09-24T00:00:00Z,2022-09-25T00:00:00Z` should.

Please keep in mind that our request sizing recommendations and savings are estimated on top of a window of data, so rather than saying "this is a recommendation and savings for 2022-09-24 -> 2022-09-25", it is more accurate to say "this is a recommendation and savings based on observed usage from 2022-09-24 -> 2022-09-25".

---

If you're just interested in efficiency (not recommendations) for short windows, you can calculate that from Allocation API (`/model/allocation`) data as long as 1h data is available. There are a few different ways resource efficiency can be considered, but my favorite is what I call "workload efficiency", calculated as `usage / max(request, usage)`. 

OpenCost includes another, equally-valid, efficiency definition that I like to call "request efficiency", if you'd rather use that. See the code for a definition: https://github.com/opencost/opencost/blob/f72d3fda552b13c94ee674d1db81117af79a2327/pkg/kubecost/allocation.go#L496-L548.
