### ISSUE TITLE
Timeout when trying to capture a bug report

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1806]
**Describe the bug**  
There are instances when you are generating a bug report from the application which cause the application to consistently "spin" while creating the report. It seems like this could be related to making Prometheus/Thanos queries directly and those queries hanging.

**To Reproduce**  
1. Try to generate a bug report on a federated cluster with a significant amount of data
2. See the forever loading page

**Expected behavior**  
Perhaps we could specify a timeout so that when the queries are hanging while making the bug report, we accept we aren't going to get that information but still get the rest of the information. If we go this route, it might be good to also leave fallback instructions on how to directly query for that information in Prometheus/Thanos.

**Comment by keithhand** [comment]
See [ZD ticket 2959](https://kubecost.zendesk.com/agent/tickets/2959) for more details.

**Comment by teevans** [comment]
@wolfeaustin - Can you take a look at this when AR is done?

**Comment by MrJW27** [comment]
@teevans / @wolfeaustin  - Do we know if this will be resolved in 1.99?

**Comment by teevans** [comment]
@wolfeaustin - Moving to the top of your notifications

**Comment by MrJW27** [comment]
@wolfeaustin & @teevans  - This is currently tagged for the V1.99 project, can you please confirm? thank you

**Comment by teevans** [comment]
@nealormsbee - Pinging for visibility

**Comment by nealormsbee** [comment]
Hi everybody. I have a solution that will add a timeout to all prometheus / thanos queries made in construction of the bug report. What do we think would be a reasonable amount of time to wait for each request?

**Comment by dwbrown2** [comment]
@AjayTripathy @keithhand @thomasvn and others may be experts here! But I believe some of these at a scale take a good bit longer than 10s.

**Comment by AjayTripathy** [comment]
Here's an idea for how to think about this:
1. What's the longest a customer will wait before giving up?
2. How many queries are there?
3. Chrome can issue up to 5 concurrent queries

wait time = (# of queries)/5 * timeout

and solve for timeout. Maybe plug in 1 minute for wait time as a baseline? 1m 30s is maximum because I believe that's the nginx timeout.

**Comment by nealormsbee** [comment]
Thanks @AjayTripathy ! That's helpful. Something to note -- these queries currently don't run in parallel at all, which will contribute to long user wait times. Do you have guidance around to what extent we can parallelize the calls without worrying about memory pressure server-side? Maybe we just parallelize the whole thing, throw a scale test at it and see what we get?

**Comment by thomasvn** [comment]
It may not be helpful to parallelize these Promethes/Thanos queries. Since we're already seeing long query response times for large scale users, parallelizing the queries could cause a larger strain on the `prometheus-server`, `thanos-query` and `thanos-store` pods which are responsible for handling the query.

@AjayTripathy I think we may want to meet with the larger support team sometime to refine which Prometheus/Thanos queries are still valuable, and which can be omitted from the bug report.

Also while we're here, @nealormsbee may I also suggest printing in the bug report the Prometheus/Thanos query that is being run, before the result of the query? Let me know if I should open a separate feature request!

**Comment by nealormsbee** [comment]
@thomasvn printing the query ahead of the results is no problem! Happy to add info that as a part of this issue.

We issue a total of 7 queries (4 prometheus, 3 thanos) to generate the bug report. I'll list them here for reference:

Prometheus queries:
- `sum(up)`
- `node_total_hourly_cost*730`
- `topk(25, count by (__name__, job)({__name__=~".+"}))`
- `topk(25,max(avg_over_time (container_memory_working_set_bytes{pod_name!="",container_name!="",container_name!="POD",namespace="kubecost"}[1d])) by (container_name,pod_name)/1024/1024/1024)`

Thanos queries:
- `avg(up) by (component, job, kubernetes_namespace)`
- `topk(25, count by (__name__, job, cluster_id)({__name__=~".+"} offset 3h))`
- `sum(count by (__name__, cluster_id)({__name__=~".+"} offset 3h)) by (cluster_id)`

I'm guessing that only one set of queries is relevant to a user, depending on whether the user runs prometheus or thanos, and the other set returns immediately due to the backing TSDB not existing. In that case, I might think a 45s timeout is reasonable for each (if all 4 prometheus queries take the max time, the user will be waiting for ~3 minutes). If we want to keep wait times down to ~1 minute, we could use a 15s timeout.

If the support team decides that some of these can be eliminated, that of course gives us more time to wait on the remaining queries!

**Comment by AjayTripathy** [comment]
Seems like sound logic to me! 15-45s works for now and we can circle back on eliminating queries later.

**Comment by dwbrown2** [comment]
cc @kwombach12 

Should we be careful about setting this too short? I'm just thinking about the large scale users that would be able to successfully pull a bug report but we time them out too early. Seems like that would be an unfortunate situation, but I may not have full context.

**Comment by keithhand** [comment]
30-45s timeouts are okay if we have the queries to check manually, if necessary. The primary reason this came up was that users on larger clusters are already unable to generate anything in a bug report, so getting us to a point where we can check at least which query is hanging would work.
