### ISSUE TITLE
Cost Breakdown of Savings Plan for compute usage line item in AWS.

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#1812]
**What problem are you trying to solve?**
Need a breakdown of the "Savings plan for compute usage". Not clear what's driving those costs. AWS doesn't break down this lined item in cost explorer. Having this breakdown in Kubecost gives more visibility into cloud costs and the data could be used for recommendations and other features.

![](https://user-images.githubusercontent.com/36980248/202565617-4c348cf9-404a-4f27-8854-0a830f58efcf.png)

**Describe the solution you'd like**
A break down of the Savings Plan cost. This item only shows costs when unblended costs are set. When using the amortized option, it reads $0.00. 

https://aws.amazon.com/blogs/aws-cloud-financial-management/understanding-your-aws-cost-datasets-a-cheat-sheet/

![](https://user-images.githubusercontent.com/36980248/202566064-67ce2f46-b9c9-47a5-ad99-9baf91b01941.png)

**Describe alternatives you've considered**
From my understanding, the Savings Plan overview and inventory page illustrates some information about what's driving the cost but it isn't clear or easy to interpret. 

![](https://user-images.githubusercontent.com/36980248/202566533-e4b326ef-7f69-46ff-aa75-2df9e03ac9cd.png)

![](https://user-images.githubusercontent.com/36980248/202567817-0e02eae0-217d-43a4-a7d7-2378ec89093a.png)

**How would users interact with this feature?**
In the assets page or advanced reporting page, customer can drill down into the "Savings for compute usage" line item. Currently do not see this item present in the assets page. 

**To Do**
Discuss with AWS support to better understand the breakdown of savings plan for compute usage.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-214) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
In general I think we can do a lot better here designing an experience to help people use savings plans. @dwbrown2 something to target for v1.100?

**Comment by Gateway85** [comment]
Context from our experience: 
What we are trying to achieve is a cost breakdown of all our resources. We are using tags in AWS to achieve that. 
But Saving Plans (like reservations and one-time marketplace purchases) cannot be tagged in AWS and are often used by multiple resources (which are tagged). 
We would like to see how the Saving Plan is consumed over the different tagged resources. 
As we pay SPs before we use them we could also learn from the past and "assume" that its ratio over the tags at time of payment will continue from last payment period. 


Additional info/requests: 
Minimum requirement: when we cluster Assets view by Tag and/or Label we need to see untagged resources with their asset type and account name so that our Finance team can at least try to assign costs to the right teams themselves. (also manual "after" tagging (and remembering those for the next occurrence of that cost) in KubeCost of items not possible to tag in AWS - would be a useful feature). 
Also when we tag the AWS resources and the Kubernetes costs we might have overlapping of costs. Might that happen and is there a solution for it?

**Comment by AjayTripathy** [comment]
Hey @Gateway85 the costs of nodes whose pricing is governed by savings plans is taken into account. As far as overlapping costs, we remove any line items billed under the "kubernetes" section from other sections of the AWS bill because they have unique resource IDs that exist as node labels.
