### ISSUE TITLE
Extend pre populated Window to 180 days+ for Container Right-sizing recommendations

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#1819]
**What problem are you trying to solve?**
Recommendations on container right-sizing & abandoned workloads page using historical data greater than 30 days (180 days+)

**Describe the solution you'd like**
More options in the drop down for the window (specifically 180days+). Or custom entry option.
![](https://user-images.githubusercontent.com/36980248/203380437-061f0906-d977-4999-ac80-5d904e41a9a3.png)

**Describe alternatives you've considered**
Making estimates based on 30day window. Querying the api directly and looking at the data.

**How would users interact with this feature?**
Navigate to Savings > Container Right-sizing and choosing a window 180 days+ or setting a custom window.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-217) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
@teevans is it easy to bring the same window options we have available in Assets/Allocation?

**Comment by mmurph3** [comment]
@teevans any updates on this? What's the level of effort here?

**Comment by teevans** [comment]
@mmurph3 - In the new Request sizing module, you can actually set a custom time window to analyze over. I want someone smarter than I to weigh in on performance implications though.

@michaelmdresser - What types of performance implications are we going to run into if we're running a 180 day query agains requestSizingV2?

**Comment by michaelmdresser** [comment]
@teevans first thing to note: if a 180d query is made, it will only be for 180d if Allocation ETL has 180d of data.

If we stick with max algorithm queries, request time should scale about linearly with window size. The thing I'd be most concerned about is memory overhead, actually, and that's hard to get a sense for without an attempt at this scale.

A good testing query is to try running a `/model/allocation?window=180d&idle=false` query. If that responds in a reasonable amount of time and the Pod doesn't fall due to memory, then I think the equivalent `/model/savings/requestSizingV2?window=180d...` query should be safe as well.

**Comment by teevans** [comment]
Thanks @michaelmdresser!!

@mmurph3 - We're going to bring over our similar window control from the allocations/assets page to this in v1.100!
