### ISSUE TITLE
Invalid ETL Data Stored - too many hours/days out of data

### ISSUE THREAD

**Issue by alnazaro** [kubecost/cost-analyzer-helm-chart#1825]
# For reproducible bugs, please provide the following

**Describe the bug**  
Since November we see a lot of hours/days with broken ETL Data for assets/allocations in all our clusters in different regions (oregon/virginia)

**Kubecost Info**
Version
1.96.0

API Version
1.96.0 (3e7021e7ba1c3d64f9f748652ca9f4b733a7b505)

**EKS VERSION 1.24**

**To Reproduce**  
1. Go to https://<kubecost>/diagnostics
2. Click on ETL Allocation (Hourly) Status/ETL Allocation (Daily) Status/ETL Assets (Hourly) Status/ETL Assets (Daily) Status

3. See error

**Expected behavior**  
all days/hours in green

**Screenshots**  
attached

[ETL-Error (1).pdf](https://github.com/kubecost/cost-analyzer-helm-chart/files/10111191/ETL-Error.1.pdf)

**Comment by AjayTripathy** [comment]
Hi @alnazaro this is likely due to prometheus downtime, cost-model downtime, or the inability of the cost-model to communicate with Prometheus during these time periods. Any instances of downtime there?

**Comment by alnazaro** [comment]
@AjayTripathy i see in log of pod error of ETL, it doesn't look like prometheus
attaching, and in histogram you can see that this error started in November, exactly when we started to get data holes
 
[ETL-outside-window.pdf](https://github.com/kubecost/cost-analyzer-helm-chart/files/10112447/ETL-outside-window.pdf)

**Comment by alnazaro** [comment]
![image](https://user-images.githubusercontent.com/34234303/204531720-088c5bae-6985-4956-a20a-c42ac3ecfc79.png)

new errors in pod

**Comment by praveenkumar0566** [comment]
I had a quick call with @alnazaro , 
- It is observed in prom the data is missing from the past week. 
- The user has an AWS-managed Prometheus integrated to kubecost 
- Kubecost endpoint is up and running in the prom targets

The next plan of action
@alnazaro will reach out to their backend team to check the PVC disk issue and who manages AWS-managed prom to check if there was any downtime or any issues.

Also regarding the PVC disk, might be not a root cause for missing data cause I see the PVC disk on the assets page

I have discussed that this is not a bug and can be communicated over the ticket.

**Comment by alnazaro** [comment]
kubecost was re-setup to use AMP as one and only source/sync and problem was resolved
