### ISSUE TITLE
[Question] Use of api proxy urls for gathering cadvisor metrics

### ISSUE THREAD

**Issue by LaikaN57** [kubecost/cost-analyzer-helm-chart#1862]
**Background**  

We got paged for high k8s api-server 5xx's. Looking at EKS CW logs we can see that most of the 503 events are associated with kubecost with a requestURI of `/api/v1/nodes/[REDACTED]/proxy/metrics/cadvisor`.

Query:
```sql
fields @message, @timestamp
| filter apiVersion == "audit.k8s.io/v1"
| filter (responseStatus.code >= 500)
| stats count(*) by user.username
```

Upon further investigation we found that the kubecost prometheus server is configured to grab the cadvisor metrics via proxy.

**Questions**

We are interested in:
1. What the rationale for proxying these requests is
2. If it is safe to grab cadvisor metrics directly from the nodes
3. Any other experience/advise you have in regards to this

**Comment by AjayTripathy** [comment]
Hey @LaikaN57 -- sorry for the late response. I believe we do that for backwards compatibility with older k8s versions. https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/charts/prometheus/values.yaml#L1191

I actually think your proposed approach makes a ton of sense. You can edit the scrape configs on your end. @thomasvn can we quickly peek at a PR getting cadvisor metrics from the nodes so we can scale test this on our end?

**Comment by LaikaN57** [comment]
Yeah, I have been trying to figure out what the proper prometheus config is to do what I am suggesting. On our non-kubecost prometheus, it seems that it is using an Endpoint for service discovery and ends up querying `http(s?)://<node-ip>:4194/metrics/cadvisor`. My prometheus knowledge is a bit lacking ATM. I will try to extract the block that we are using in a bit. Standby.

**Comment by thomasvn** [comment]
@LaikaN57. Correct that Kubecost’s bundled prometheus is getting cAdvisor metrics through the k8s api server. The screenshot below shows kubecost’s bundled prometheus targets in the UI: `$ kubectl port-forward svc/kubecost-prometheus-server 8080:80`

<img width="1408" alt="prometheus-targets-annotated" src="https://user-images.githubusercontent.com/11251627/207704150-6d6c36a9-f01f-44a7-bdbb-9e1b4b3abfc0.png">

Why do you think your Prometheus requests to the k8s api server are resulting in numerous 5xx? Is it possible that Kubecost’s bundled prometheus is scraping too much and too frequently for the API server to handle? It may be possible to adjust your configuration to reduce the number of 5xx errors. I ask because getting cAdvisor metrics through the k8s api server seems to be standard, and what the upstream Prometheus Helm Chart does too (shown [here](https://github.com/prometheus-community/helm-charts/blob/8cf2418c5c27f60c297fbd51f8a1adf844f536bf/charts/prometheus/values.yaml#L709-L748)).

Regardless, it would be interesting to provide an option to directly scrape the node’s Kubelet for cAdvisor metrics instead of going through the api server! I’ll look into that now.

**Comment by AjayTripathy** [comment]
Hey @LaikaN57 -- happy new year! Were you able to migrate to this? We're available to help you if you still need it.

**Comment by LaikaN57** [comment]
I have not applied a fix yet, but I do have a path forward. Just people/time resourcing constraints right now. Thanks for answering the question. I tend to agree that proxying is standard. It will be interesting to see if my alternate route is better for performance or not. No follow up needed for now. I will re-open if needed.
