### ISSUE TITLE
Selecting a cluster on the Allocation page doesn't always filter a single cluster

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1879]
**Describe the bug**

On the allocation page, if you aggregate by cluster and select an option listed, the next drill-down is based on the cluster name, not the cluster id. Some users have common cluster names, resulting in the next drill-down showing more costs than expected. 

**To Reproduce**

1. Deploy a federated system using common values for `kubecostProductConfigs.clusterName`
1. Go to `/allocations?agg=cluster&idle=separate` and select a cluster. Note the price of the individual line item.
1. See that the total cost in the following report is larger than the previous individual cluster.

**Expected behavior**

After selecting an option to see more info, the following report should only display the results from that option. This looks like how the Assets report is already configured to work.

**Screenshots** 
![image](https://user-images.githubusercontent.com/43491549/207724502-c3dec506-7d65-4ca7-9d8f-7d040b602f67.png)
![image](https://user-images.githubusercontent.com/43491549/207725784-a9809f25-0e9d-4a73-a095-a1b2229dd616.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-227) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
thanks for reporting, keith! we've always recommended cluster names should be unique. do you know why they aren't in this case?

**Comment by keithhand** [comment]
I thought the cluster name itself was more for labeling uses, and the cluster id needed to be unique, though I might be misunderstanding that. In cases where a user might have different "flavors" of the same cluster, they might use the same "cluster name" to identify those while also using a unique cluster id; for example, `us-west/us-west-dev` and `us-west/us-west-prod`. But it sounds like the cluster name and the cluster id are expected to be unique. Is there a reason we don't refer to one unique value instead of having 2 [potentially] identical unique values?

**Comment by dwbrown2** [comment]
@keithhand you're totally right, it's way more important for cluster-ids to be unique... I just have always recommend both of these values are unique to make it easier to distinguish between clusters.  Your proposal make sense to me though.

cc @nealormsbee and @nikovacevic for input since this may touch both of their worlds

**Comment by nikovacevic** [comment]
In my opinion this is totally a matter of meeting user expectations. Sounds like we have two groups of users:  one group that wants "cluster" to mean "cluster name" (because the IDs are not important to them, but they know the names), and now one group that wants "cluster" to mean "cluster ID" (because they know the IDs and those are unique, but the names are not unique).

For drill-down, we can probably hack in a quick fix like filtering by `cluster-id/cluster-name` and requiring both on-click. That should always result in only a single cluster being selected.

For the manually applied filter, it's up to the user to know what to enter to get the results they want, and I don't see a way around that.

**Comment by nikovacevic** [comment]
Let me know if we want to prioritize this work for a particular release. It'll require light BE work and light FE work, I expect.

cc @Adam-Stack-PM

**Comment by AjayTripathy** [comment]
> For drill-down, we can probably hack in a quick fix like filtering by cluster-id/cluster-name and requiring both on-click. That should always result in only a single cluster being selected.

That seems like the right solution to me! Feels like enough of an edge case where this can wait for v1.101

**Comment by Adam-Stack-PM** [comment]
@AjayTripathy Do you want this promoted for v1.102 or v1.103 or should I mark it as p2 and pick it up whenever we have extra capacity?  CC: @kwombach12

**Comment by AjayTripathy** [comment]
@kwombach12 don't know if you'd agree but I'd call this a bug for triage in the 102 burndown.

**Comment by kwombach12** [comment]
Definitely a bug for 1.102. Ill add to our doc

**Comment by Adam-Stack-PM** [comment]
Tracking. P1 for v1.102.
