### ISSUE TITLE
Container Request Right Sizing API (v2) with Argo Rollouts CRD fails for 'algorithmCPU=quantile' parameter

### ISSUE THREAD

**Issue by praveenkumar0566** [kubecost/cost-analyzer-helm-chart#1890]
---
**Describe the bug**  
Container Request Right Sizing API (v2) API  call failing for Argo Rollouts CRD deployment [https://argoproj.github.io/argo-rollouts/](https://argoproj.github.io/argo-rollouts/)  for `algorithmCPU=quantile` parameter but works for `algorithmCPU=max`.

Error:

```
curl -G \
-d 'algorithmCPU=quantile' \
-d 'qCPU=0.99' \
-d 'algorithmRAM=max' \
-d 'targetCPUUtilization=0.5' \
-d 'targetRAMUtilization=0.8' \
-d 'window=3d' \
--data-urlencode 'filter=namespace:"coinmaster"' \
${KUBECOST_ADDRESS}/savings/requestSizingV2
```

**See Error** : **Recommending requests from data: failed to approx CPU quantile: nil CPU histogram** 

**To Reproduce**  
Deploy Agro Rollout - https://argoproj.github.io/argo-rollouts/
Enable https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L345

Fire API call
Ex: 
```
KUBECOST_ADDRESS='http://localhost:9090/model'
curl -G \
-d 'algorithmCPU=quantile' \
-d 'qCPU=0.99' \
-d 'algorithmRAM=max' \
-d 'targetCPUUtilization=0.5' \
-d 'targetRAMUtilization=0.8' \
-d 'window=3d' \
--data-urlencode 'filter=namespace:"coinmaster"' \
${KUBECOST_ADDRESS}/savings/requestSizingV2```
```

**Expected behavior**  
The API should fetch the data for the parameter 'algorithmCPU=quantile' 

**Screenshots**  
![1fva81lc90jreh-image](https://user-images.githubusercontent.com/102574445/210591767-1196b997-e5e0-4748-94e6-1828a54a6bad.png)

Additional Info
- ContainerStatsEnabled has been enabled
- The container has the data
- API works for the same namespace for the parameter 'algorithmCPU=max' 

Ref slack discussion - https://kubecost.slack.com/archives/G01MN4R06MB/p1672251573646919

**Comment by teevans** [comment]
@michaelmdresser - Would you mind taking a look?

**Comment by michaelmdresser** [comment]
For the sake of thoroughness, what happens when you set `algorithmCPU=max` and `algorithmRAM=quantile&qRAM=0.99`? I expect a similar-looking error but I want to be absolutely certain.

---

Onto more specific debugging.

Is it possible to get a response from:
- `/model/containerstats/quantiles?window=2d&q=0.95&resource=cpu-cores` (may be very large, I apologize for the lack of filters available here)
- `/model/allocation?window=2d&accumulate=true&idle=false&filter=namespace:"coinmaster"`

Alternatively, if you have a live dev cluster/environment that I can get access to with a repro set up, I can do some digging on my own.

I'm trying to figure out how the Allocation Properties compare with the metadata being captured by the ContainerStats pipeline. My current theory is that Argo Rollouts is causing us to fill in different metadata in ContainerStats and Allocation but I'm not sure of that yet. 

In theory it shouldn't be possible to end up with nil individual histograms at this point but clearly its happening. At the very least I'd like to see the `/model/allocation` response's properties for one of the Argo-managed Pods.

**Comment by michaelmdresser** [comment]
Alternatively, I could probably work with a dump of the `container-stats` and `etl` directories from disk.

**Comment by praveenkumar0566** [comment]
I have requested the ETL dump to the user.

**Comment by praveenkumar0566** [comment]
@michaelmdresser I have DM the attachment of the ETL dump

**Comment by michaelmdresser** [comment]
Fix PR is out: https://github.com/kubecost/kubecost-cost-model/pull/1158

Huge thanks to @praveenkumar0566 for working with the customer to get a dump of their ETL and ContainerStats data, it made debugging this issue easy.
