### ISSUE TITLE
Helm chart arm support 

### ISSUE THREAD

**Issue by rhysxevans** [kubecost/cost-analyzer-helm-chart#1897]
Hi

We are looking to deploy a number of arm clusters, however the bitnami config reloader pod does not support arm (at present I don't think bitnami supports arm at all). Can we move to a cross architecture config reloader ? If so is it a simple image update or is there more to it?

I am happy to help with testing etc, any thoughts are appreciated

Thanks

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-25) by [Unito](https://www.unito.io)

**Comment by rhysxevans** [comment]
https://github.com/kubecost/cost-analyzer-helm-chart/blob/3ecf9098346bd63baaf6b0a7903bb49bbcd0ef86/cost-analyzer/values-eks-cost-monitoring.yaml#L154. Is where the issue is from what I can see, I may be wrong

**Comment by teevans** [comment]
@AjayTripathy  - Any thoughts here?

**Comment by AjayTripathy** [comment]
Thanks for this note @rhysxevans -- I think the configmap reloader is optional for prometheus, just making it so the original configmap update happens without restart. We'll look into this but for now I think you can just set this to false and restart prometheus, since we only update the configs one time and not dynamically.

**Comment by rhys-evans** [comment]
Great thanks

**Comment by teevans** [comment]
Closing out for now. Please re-open if we need to do anything else!

**Comment by Adam-Stack-PM** [comment]
@teevans Looks like we missed closing this issue. Closing now.  Reopen if needed.
