### ISSUE TITLE
kubecost-prometheus-server unavailable

### ISSUE THREAD

**Issue by hyj-github** [kubecost/cost-analyzer-helm-chart#1951]
**[problem description](javascript:;)**
    I used Prometheus, which came with kubecost. Observed a sudden spike in Prometheus disk usage on February 1 (from 10 gigabytes to 20 gigabytes) and continued growth thereafter; Before February 1, usage remained stable (around 9G). kubecost-prometheus-server was repeatedly restarted due to memory overflow from loading too much data from disk.
   kubecost is no longer available. Is there a solution?

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-4) by [Unito](https://www.unito.io)

**Comment by hyj-github** [comment]
disk usage
![image](https://user-images.githubusercontent.com/54680729/216572895-b9fceac6-9c09-46a2-a7f5-ed654fe82127.png)

**Comment by hyj-github** [comment]
The container continues to restart. An OOM error is reported.
![Uploading Prometheus重启.PNG…]()

**Comment by thomasvn** [comment]
Thanks for reporting @hyj-github! Can you think of any changes that may have been made since Feb1?

- increased number of clusters monitored by Kubecost?
- increase in service-endpoints that Prometheus is scraping?
- adjustments to the Prometheus scrape_config?

Also, I think this debugging would be most quickly resolved by one of our dedicated support engineers. Would you mind logging a ticket with [support@kubecost.com](mailto:support@kubecost.com)? Be sure to include a link to this GitHub issue so you don’t have to document your issue twice! Please note that all communication will be handled via that ticket moving forward to ensure privacy of your data as we work to resolve the issue.

**Comment by hyj-github** [comment]
> Thanks for reporting @hyj-github! Can you think of any changes that may have been made since Feb1?
> 
> * increased number of clusters monitored by Kubecost?
> * increase in service-endpoints that Prometheus is scraping?
> * adjustments to the Prometheus scrape_config?
> 
> 

Other than the addition of the container limit on January 19th, nothing has been changed.It was normal then.

**Comment by thomasvn** [comment]
@hyj-github I see you've submitted a ticket to support@kubecost.com, so we can continue the conversation there!

In the ticket, we'll work to investigate the underlying cause of this memory/disk spike. However to immediately resolve the current Prometheus OOM, I'd recommend following this [tuning guide](https://docs.kubecost.com/general/resource-consumption) and increasing Prometheus's memory limits and PV size.

**Comment by hyj-github** [comment]
I've found that Prometheus's pod has frequent memory usage spikes that can cause reboots. What's the reason?

**Comment by hyj-github** [comment]
I have solved this temporarily by increasing resources, but would like to know some solutions other than increasing resources.

**Comment by teevans** [comment]
@thomasvn - Am I good to close this out in favor of Zendesk here?

**Comment by thomasvn** [comment]
Yes, @hyj-github let's continue the conversation via Kubecost Support email. Once we identify the underlying cause of the memory spike we can update this Github Issue.
