### ISSUE TITLE
Unclear what "Allocate Idle Resources" setting does

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1987]
**Describe the bug**  
After toggling the Allocate Idle Resources options or enabling the flag `kubecostProductConfigs.defaultIdle=true`, no change seems to be happening to any allocation report.

**To Reproduce**  
1. Set "Allocate Idle Resources" in the settings, or use the helm flag `--set kubecostProductConfigs.defaultIdle=true`
2. Verify that the option is enabled in the Settings screen on a fresh load
3. See no change in allocation reports

**Expected behavior**  
Idle resources are allocated by default on allocation reports after toggling that option in the settings. If there is another explanation for what is expected to change when that option is toggled, that would be great too.

**Screenshots**  
<img width="980" alt="image" src="https://user-images.githubusercontent.com/43491549/219248871-51569b75-f741-4d50-b3c3-ea2d53a3f5ad.png">

<img width="412" alt="image" src="https://user-images.githubusercontent.com/43491549/219248947-2fed1dcb-a0ea-4d75-8b98-6c9647444b7b.png">

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-269) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
Hey @keithhand what happens if this is set from helm?

**Comment by wamak9** [comment]
@AjayTripathy  -- Same behavior as from UI. Nothing changes on the allocation page.

**Comment by keithhand** [comment]
The toggle is working, but I don't notice any change in reports happening. The flag also seemed affected by [this bug](https://github.com/kubecost/cost-analyzer-helm-chart/issues/1921). I needed to disable it manually after setting the flag to false.

**Comment by AjayTripathy** [comment]
@nealormsbee can you take a look?

**Comment by nealormsbee** [comment]
Took a peek, we're definitely not using it on the frontend. It looks like we used to, back when we were making calls to `/aggregatedCostModel`. It seems like this is meant to dictate the default parameter for `shareIdle` in allocation queries.

We can set up the frontend to use that default for all requests where it isn't overridden, but I have a structural question there: should the config define the default way that the client makes queries to the server, or the default way that the server interprets under-specified queries?

**Comment by AjayTripathy** [comment]
The config should be about what the frontend sends to the backend, not how the backend interprets this @nealormsbee . Feel like that's a super quick one.

**Comment by nealormsbee** [comment]
It should be quick, and I am fine with implementing it that way to fix the immediate problem.

>The config should be about what the frontend sends to the backend, not how the backend interprets this @nealormsbee 

My question is whether that architecture makes any sense. There's a Helm chart config, which lives *on the server*, which the client reads *from the server*, so that it can send that same parameter *back to the server* in queries. That seems to me (1) inefficient and (2) like we're giving ourselves a nice rake to step on (as in this exact scenario / issue). Is there some context I'm missing here?

**Comment by nealormsbee** [comment]
Need one piece of input here. Allocation reports have 4 options for how we deal with idle:

- Hide idle
- Treat idle separately
- Share idle by cluster
- Share idle by node

When we're not sharing, we default to treating idle separately. What should we default to when we *are* sharing? By cluster or by node? I'll just roll forward with "By cluster" rather than blocking here, but if there's a reason to prefer one or the other then we can go with that.

**Comment by kwombach12** [comment]
@nealormsbee I think defaulting to cluster makes sense for this case. Ideally, we'd update that helm flag to be more clear in the future
