### ISSUE TITLE
Missing Cost Estimates and Breakdowns for Unclaimed Volumes in Kubecost's Cost Savings Recommendations

### ISSUE THREAD

**Issue by abidiqbalxgrid** [kubecost/cost-analyzer-helm-chart#1994]
**What problem are you trying to solve?**
Kubecost's recommendations for cost savings include providing an estimate of potential savings when taking actions such as right-sizing cluster nodes and reserved instances. However, no cost estimate is given for unclaimed volumes, and the list of unclaimed volumes lacks a cost breakdown, making it difficult to determine the cost of each individual unclaimed volume.

**Describe the solution you'd like**
I would like Kubecost to provide cost estimates for unclaimed volumes and include a cost breakdown for each volume in the list of unclaimed volumes. This would allow users to better understand the cost of each volume and make informed decisions about how to optimize their resource usage to further reduce costs.

**Describe alternatives you've considered**
No alternative solution so far.

**How would users interact with this feature?**
On the Kubecost savings page, users would view estimated savings for unclaimed volumes. By clicking on "manage unclaimed volumes," users would be able to access a page that provides detailed information on all unclaimed volumes, including their name, storage class, size, and cost up to that point.

**Estimated savings on Right-Size cluster nodes**

![Screenshot from 2023-02-22 00-29-53](https://user-images.githubusercontent.com/109594972/220440460-52cce582-2bf4-44b2-a153-85b1474428d7.png)

**No savings estimated for unclaimed volumes**

![Screenshot from 2023-02-22 00-30-22](https://user-images.githubusercontent.com/109594972/220440531-e0464e03-c8f3-4687-b804-066985655693.png)

**No cost breakdown for unclaimed volumes**

![Screenshot from 2023-02-22 00-34-03](https://user-images.githubusercontent.com/109594972/220441278-2c449cd6-28eb-4136-b3de-14a5b29f34d5.png)

**Comment by thomasvn** [comment]
@nealormsbee Thoughts? Does the API backing this "Unclaimed Volumes" page have enough data to present estimated savings?

**Comment by dwbrown2** [comment]
This looks like close to a bug to me. @nealormsbee any input?

cc @Adam-Stack-PM for tracking

**Comment by teevans** [comment]
@Adam-Stack-PM - Neal is out, can we track this for burndown this week?

**Comment by nealormsbee** [comment]
@thomasvn we should be able to estimate those savings from the backing API. There are two parts to this issue:

1. There is no cost shown on the Savings page’s Unclaimed Volumes card.

We don't show number values for $0.00 or negative-dollar estimated savings, instead simply showing "explore savings". I'd need to try reproducing the be sure, but it seems likely that our estimated savings for underutilized PVs is negative, which is why that card does not show a number.

2. Table on the Unclaimed Volumes page doesn't have a cost column.

This seems like something we can / probably should provide…I’m moderately confident that we’ve never had such a column, so I wouldn’t call it a bug or regression so much as an obviously beneficial enhancement.
