### ISSUE TITLE
ability to hide beta features

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#2063]
**What problem are you trying to solve?**
Operations teams get questions from kubecost users regarding beta features in kubecost.

These functions can cause perception issues that kubecost is not ready for GA.

**Describe the solution you'd like**
Ideally a helm setting. but also there is a good mock-up here:
https://github.com/kubecost/cost-analyzer-helm-chart/issues/1929

**Comment by dwbrown2** [comment]
Definitely see the value in this... a couple initial questions that come to mind:

1. Would this be both beta pages + beta features within GA pages? I'm guessing so, but is one category higher priority?
2. Would we hide beta pages in navigation outright or show a "hidden due to settings" mesage? Former seems cleaner but might confuse users if they suddenly disappear. 
3. Are there currently GA features teams would want hidden? I imagine there are but I think that's a separate use case.
4. Do we want to make this an Admin Only feature? Seems reasonable. 

cc @kwombach12

**Comment by jessegoodier** [comment]
Good questions. Maybe need to classify "new feature launch beta" vs everything else?

**Comment by jessegoodier** [comment]
There are open issues for hiding certain cards. 

Certainly the local cluster-only savings cards and cluster-sizing cause similar operations' teams issues with questions on why they don't work or why suggest nodes that aren't viable. 

By operations issues: CFO questions on why they haven't implemented X? 
Example is they need nodes that have higher network capacity or GPUs.

**Comment by jessegoodier** [comment]
ability to hide savings cards in 104, toggle for alpha features added in 103
