### ISSUE TITLE
Controller filter on Request Sizing UI does not work

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#2075]
**Describe the bug**  
It isn't possible to use the "controller" filter via the Request Sizing UI. This can also occur if you are selecting the "Request Sizing" link from within a `/details` screen, i.e. 
<img width="578" alt="image" src="https://user-images.githubusercontent.com/43491549/227016955-60a3f22e-63f6-464c-ac08-b09db3c272e0.png">
https://demo.kubecost.xyz/details?name=deployment:kubecost-cost-analyzer&type=controller

This is because the filter that is being applied to the API is `controller` and the API is expecting `controllerName` ([reference](https://docs.kubecost.com/apis/apis-overview/filters-api)). 

**To Reproduce**  
1. Visit the Request Sizing Savings page and try to filter using the "controller" type.
2. See error:
> Error parsing V2 filter: parsing filter: 1 error occurred: * at 'controller': expect filter field

**Expected behavior**  
The UI filters the details based on the controller name when selecting the controller filter. 

**Screenshots**  
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/43491549/227017032-56a8b55b-06be-44db-b961-90f304887b84.png">

**Comment by kwombach12** [comment]
@Adam-Stack-PM this is a P0 for bug fixes next week

**Comment by MikeHsuMlytics** [comment]
Hi Kubecost Team:
i'm suffering the same problem in Request right-sizing recommendations page (v1.101.3). 
the GET FilterV2 API seems be called wrongly in frontend side.
here are some not working filter fields below :
- service
- controller
- pod

**Comment by Sharma-Rajat** [comment]
I have the same issue as well. Unable to filter by workload due to the controllerName issue.

**Comment by teevans** [comment]
@nealormsbee - Did we already fix this recently?

**Comment by nealormsbee** [comment]
@teevans I believe so. I took these steps:

- Run the nightly build
- Navigate to Cost Allocation
- Aggregate by Controller
- Click into details for `deployment:kubecost-cost-analyzer`
- Click the Request Sizing link pictured above

And the filters appear to apply correctly:

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/981904/227599610-dd673a34-bb33-4e84-9226-b7380158ca63.png">

<img width="722" alt="image" src="https://user-images.githubusercontent.com/981904/227599647-30e45e54-74cf-4dc8-95d8-dd7b715cd836.png">


That said, this may be due to switching back to v1 filtering, which we may need to revert. Let's keep this open until we confirm it works with the V2 filter scheme as well.

**Comment by Adam-Stack-PM** [comment]
https://kubecost.atlassian.net/browse/BURNDOWN-26

**Comment by teevans** [comment]
@keithhand - Can you try to repro on nightly and see if you're still seeing this issue?

**Comment by nealormsbee** [comment]
It won't be on nightly because it's specific to the FE malformatting a request to the V2 filters, which nightly doesn't have.

We're switching BACK to using the V2 filters, which would recreate this bug. But there's a PR to remedy it here: https://github.com/kubecost/cost-analyzer-frontend/pull/1874

**Comment by nealormsbee** [comment]
This should be fixed now. @keithhand can you try to repro on nightly and see if you're still seeing this issue?

**Comment by keithhand** [comment]
@nealormsbee LGTM

**Comment by nealormsbee** [comment]
Woohoo! 🙌
