### ISSUE TITLE
Whats the impact of removing the auto mount of access token for kubecost service accounts

### ISSUE THREAD

**Issue by ghost** [kubecost/cost-analyzer-helm-chart#2078]
I have deployed the kubecost on aks, but microsoft inbuilt cloud defender security raised the high severity vulnerability on auto mount of access tokens for service accounts.

I would like to know on the following items:

Does kubecost supports disabling automount of sa tokens. if not , is it on future roadmap.
What will be the impact of mounting the tokens manually but on different mounted path.

**Comment by vinnieatnzta** [comment]
I have the same issue as well. Unable to deploy by diabling auto mounting of service token

**Comment by AjayTripathy** [comment]
@mackmittalwk we need API server access to function. This is read-only permission by default, since we need to enumerate cluster resources to understand what's running in the cluster and how to cost it out.

I guess if you mount it manually this may work; that being said, it's best practice to disable automount only if pods don't need APIserver access, which we do need.
