### ISSUE TITLE
UI Related Issues

### ISSUE THREAD

**Issue by niketatbar** [kubecost/cost-analyzer-helm-chart#2105]
Hello Kubecost Security Team,

My name is Niket and I am a cyber security researcher. I have noticed one UI related issue in your website due to which any user cannot access some functions of the website properly. The details for which are as follows.

In the 'Setting' section of the account, whenever any user tries to edit details of his team he can not access the functions like 'Cancel Invite' or 'Remove Member' due to overlapping the side panel on 'Cancel Invite' or 'Remove Member' sections. I have attached a video explaining the same. This issue remains the same even if you use your account from a browser in an android or ios device.

**Comment by kwombach12** [comment]
@ausmith Can you take a look at this?

**Comment by ausmith** [comment]
@niketatbar we do not see the video you mentioned, mind adding that? I would also be curious what the `Kubecost Info` section in the Settings page indicates and the domain you are hitting when you have this experience. Your description makes this sound like a "smaller screen" (or mobile view) issue rather than a security one, but I would appreciate the video showing your experience to verify that impression.

**Comment by niketatbar** [comment]
https://drive.google.com/file/d/16a1EQsZgypij3SB0q0Z3CAcboibzpzaq/view?usp=drivesdk

**Comment by ausmith** [comment]
Thanks for reporting Niket! Definitely a bug. We'll get this fixed up in the near future.
