### ISSUE TITLE
Stacked Bar Chart - Option for Fixed-Location Bar Groups

### ISSUE THREAD

**Issue by kc-adawson** [kubecost/cost-analyzer-helm-chart#2171]
**What problem are you trying to solve?**

As of 1.102.2 the stacked bar chart is sorted by cost, and when there are workloads that are close to the same price they can switch in and out of order in the UI. 

This can get hard to interpret for some people, so it would be great to have an option to "fix stacked bar positions" so that they are consistent on the graph over time, which would allow for visual identifying of trends for each group to be easier

<img width="792" alt="2023-04-21_16-01-50" src="https://user-images.githubusercontent.com/101200254/233725953-7193e92a-bb6d-4e6c-a0e0-a21c951fcef5.png">

**Describe the solution you'd like**
If people think fixed stacked bars are the right answer I'm happy with making it the default. 

If there is a reason for having both a non-fixed stacked bar where the sections move instead of making them fixed, just adding "fixed stack bar position" as a checkbox option would solve the problem for users. Then they could save their reports like that or set it as the default.

**Comment by mbolt35** [comment]
There are a lot of specific assumptions being made here that I don't think apply universally:
* Each graph color shows the aggregation which is not 1-1 with a "workload."
* It is not guaranteed that each day will contain the same top 10 aggregations. 
  * Even assuming that each day is guaranteed to have the same top 10, It is unclear to me how a fixed order would allow them to see trends, as each bar position affects the starting position of the next bar, identifying trends visually for each item requires a fixed relative starting point. 
  * If one aggregation is removed from the top 10 and another one added, where is the proper place to insert the new aggregation color as to not affect "fixed" position of other bars? 

Just a suggestion, but it seems to make a lot more sense to add more data visualizations instead of adding a global checkbox that attempts to shoe-horn in a semantically incompatible option for data that doesn't follow the specified use-case. 

For example, a great way to examine trends relative to other aggregate data is to pick the top aggregations over 60d to ensure that the same 10 data points are consistent across the entire visualization, and use line graph.

**Comment by kc-adawson** [comment]
@mbolt35 That sounds like a more thought-out plan, I agree with all your points. I'm all for more data visualization options to help reach the goal of easy visual clarity for different users.

**Comment by chipzoller** [comment]
Closing, stale. For any future enhancements or bugs which do not pertain specifically to the Helm chart, please log them in the [features-bugs](https://github.com/kubecost/features-bugs/) repo.
