### ISSUE TITLE
Labels are not listed in the properties of running resources

### ISSUE THREAD

**Issue by conlon** [kubecost/cost-analyzer-helm-chart#2222]
---
# For reproducible bugs, please provide the following

_Note: This bug was first observed while running on v1.99.0, and still exists on v1.102.2_

**Describe the bug**  
In the Allocation API, when accumulate=true and window > 1h , labels are not listed in the properties of *running* resources. Resources which have stopped do list their labels.

**To Reproduce**  
1. Go to `/model/allocation?window=1h&filter=label[<key>]:"<value>"&accumulate=true`. Observe that all resources list their labels. (Find "name" and find "labels", compare number of results).
_Note: the filter here is not required nor does it affect the bug behavior, but serves to limit the results for parsing, and it also proves that all resources being returned do have labels that aren't being listed in the results._
2. Go to `/model/allocation?window=2h&filter=label[<key>]:"<value>"&accumulate=true`. Observe that only some resources list their labels.
3. Run `kubectl describe pod <podname>` for resources with and without labels. Observe that 
- pods which are not running have their labels listed
- running pods do not list their labels

**Expected behavior**  
All resources should list their labels, regardless of status.

**Screenshots**  
N/A

**Collect logs (please complete the following information):**
- Run `helm ls` and paste the output here:
Unsure how to run this against my cluster. Happy to provide more info upon request.
- If the pod is stuck in init, run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-init` and paste output here:
- If a page is broken or not loading, open your javascript developer console and paste the ouput here:
- Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-server` and paste the output here:
```
$ k logs kubecost-cost-analyzer-5d96f5d99b-ntvvn -n kubecost -c cost-analyzer-server
error: container cost-analyzer-server is not valid for pod kubecost-cost-analyzer-5d96f5d99b-ntvvn
```
- Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-model` and paste the output here:
```
This has a massive result, but I can share upon request
```
- Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-frontend` and paste the output here:
```
same as above
```

**Please share the support case, if any**  
Conversation with support in slack here: https://kubecost.slack.com/archives/CLFV60Y90/p1682368914828119

**What impact will this have on your ability to get value out of Kubecost?**
This is blocking my ability to query for daily costs broken down by team (label). This is essential for reporting to our development teams what costs they are responsible for.

---
# For feature requests, please provide the following:

**What problem are you trying to solve?**  
I'm trying to get daily cost metrics broken down by dev team (via a label)

**Describe the solution you'd like**  
Consistent reporting of labels

**Describe alternatives you've considered**  
Without this bug being fixed, if I want to report this information, I need to query kubecost 24 times and accumulate the results myself. Otherwise dev teams need to sift through all services they own by name, rather than being able to group by team label. This does not allow us to aggregate by team and compare cost per team, which the business desires.

**Please share the support case, if any**  
Conversation with support in slack here: https://kubecost.slack.com/archives/CLFV60Y90/p1682368914828119

**How would users interact with this feature?**
Same as they do today, but with accurate and comprehensive results.

**What impact will this have on your ability to get value out of Kubecost?**
This is blocking my ability to query for daily costs broken down by team (label). This is essential for reporting to our development teams what costs they are responsible for.

**Comment by kwombach12** [comment]
Thanks @conlon I have logged this bug and we will try to tackle this in the next release!

**Comment by seeeun-cho** [comment]
I have a similar issue +1 that some of the pods having labels are not listed in the properties in the API response.
@kwombach12

**Comment by ameijer** [comment]
Hello @conlon! The short story is that labels are dropped when you aggregate or accumulate, but you can direct the system to keep them. 

Your observation of the shorter term labels being included is due to the fact that for a 1 hour query window, no accumulation actually occurs, but with 2+ hour windows, the accumulation transform must be applied. We drop labels by default because with large sets of labels and/or deployments, carrying the labels through all these transforms can get really compute heavy for information that not all users actually leverage, so by default we do not do it. 

The good news is there are a few options here for you:
1. There are new namespaceLabel and namespaceAnnotation fields in the properties of the allocation object. These are always computed. These will have the intersection of namespace the labels and annotations across all the objects you are aggregating or accumulating by. If the namespace labels are all you are after, I would recommend this route. 
2. If you require more fine grained labels (i.e., on the pod level), then you can use the includeAggregatedMetadata=true query param in those URLs. Just be aware there is additional computation required. We need the PR I referenced above to go in first though.

**Comment by ameijer** [comment]
@conlon the includeAggregatedMetadata fix should be available in the next 105 release candidate!
