### ISSUE TITLE
Empty page on `/cluster-inspect` view when using certain windows

### ISSUE THREAD

**Issue by thomasvn** [kubecost/cost-analyzer-helm-chart#2285]
## Describe the bug
When on the `/cluster-inspect` view, I see an empty page when setting certain windows:

* "Today"
* "Yesterday"
* "Last week"
* "Last month"
* "Last 24h"
* "Last 6 months"
* "Last 12 months"

## To Reproduce
1. Go to Kubecost Overview Page
2. Click on a Cluster under `Clusters > Cluster breakdown`
3. Adjust the window from "Last 7 days" to "Last week"

## Screenshots
Looks correct:
<img width="1259" alt="Screenshot 2023-05-25 at 5 46 00 PM" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/11251627/eb8748a8-5b9a-4c2e-b097-0c5e7b4f1e92">

Looks incorrect:
<img width="1259" alt="Screenshot 2023-05-25 at 5 46 23 PM" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/11251627/acce7a2e-f187-4d24-a1f1-50906f559db8">

**Comment by kwombach12** [comment]
@nealormsbee correct me if im wrong, but I believe we have disabled the options which don't work in 104

**Comment by thomasvn** [comment]
@kwombach12 Looking at nightly, and it seems all the options are still available in this view. The only ones which are still not working for me are:

* "Last week"
* "Last month"
* "Last 6 months"
* "Last 12 months"

**Comment by kwombach12** [comment]
@nealormsbee Can you take a look at this? I thought we disabled options that dont work?

**Comment by thomasvn** [comment]
@nealormsbee As an update, in v1.104.1 the only ones which are still not working are:

* "Last week"
* "Last month"

**Comment by nealormsbee** [comment]
I think I see the problem. I don't think it's a matter of disabling more options...the issue is that on clickthrough, our Window parameters doesn't come along for the ride. So with "Last month" data, you have clusters that may not have existed in the last 7 days. But on clickthrough, that's the window you get.

My hunch is that this happens when we click through to a cluster that we were tracking in the past, but not in the last 7 days.
I'm not currently able to reproduce on demo.kubecost.xyz, which is where it looked like this originally cropped up based on the screenshot.

Do we have a reliable way to reproduce and test a possible solution?

**Comment by thomasvn** [comment]
@nealormsbee Hm, I'm seeing the issue in the demo environment. For example, the first query works, but the second doesn't:

* `/cluster-inspect?clusterId=kc-demo-prod&cloudId=kc-demo-prod&window=week`
* `/cluster-inspect?clusterId=kc-demo-prod&cloudId=kc-demo-prod&window=lastweek`

**Comment by rayhatfield** [comment]
The "Last week" and "Last month" cases are failing because the validation schema on the frontend expects/requires camel case (e.g. `"lastWeek"`) but the parameter is all lowercase (`"lastweek"`). [PR 129](https://github.com/kubecost/kubecost-frontend/pull/129) ☝️ updates the schema accordingly.
