### ISSUE TITLE
Total cost increases when setting custom shared resources AND sharing idle by cluster or Node

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#2359]
**Describe the bug**  
When sharing idle by cluster or node AND setting custom shared resources (namespaces), the total costs on the current aggregation changes

**To Reproduce**  

1. Aggregate by NS and last 7 days and take note of the total costs.
2. Click on 'edit' and apply custom shared resources (ns') and share idle by cluster or node.
3. Take note of the new total costs.

[Shared custom resources set & sharing idle by cluster](https://demo.kubecost.xyz/allocations?sharedNamespaces=kube-system%2C+kubecost&idle=shareByCluster)
[No shared custom resources set & sharing idle by cluster](https://demo.kubecost.xyz/allocations?idle=shareByCluster)

**Expected behavior**  
I expect the total costs not to change when sharing idle and setting custom resources. This should just allocate the total costs differently.

**Screenshots**  

**What impact will this have on your ability to get value out of Kubecost?**
This impacts data accuracy and integrity to the user. 
Affects the ability to do accurate charge back/show back in multi-tenant environments.

**Comment by mmurph3** [comment]
cc @kwombach12

**Comment by thomasvn** [comment]
@mmurph3 Thanks for reporting! I've logged this as a bug and we'll plan on fixing in the next release.

**Comment by mmurph3** [comment]
@thomasvn thanks. Enterprise customer is willing to use a custom image. This is time sensitive. Would be ideal to have before next release. We can discuss internally to prioritize this. 

cc @kwombach12 @teevans

**Comment by nik-kc** [comment]
The problem here is that the shared cost calculations are incorrect. All other costs (CPU, RAM, etc.) remain consistent, regardless of settings.

The issue is somewhere in the `AggregateBy` [code](https://github.com/opencost/opencost/blob/develop/pkg/kubecost/summaryallocation.go#L528).  The only difference in `AggregrateBy`, between the two queries linked in the issue description, is the value of `Share` [here](https://github.com/opencost/opencost/blob/develop/pkg/kubecost/summaryallocation.go#L650).

I'm still investigating the exact cause of this issue. If I don't get to the bottom of it soon, I'll bring in someone more familiar with the `AggregateBy` code.

**Comment by mmurph3** [comment]
@nik-kc I appreciate the work here. Any updates?

**Comment by nik-kc** [comment]
@mmurph3 Unfortunately a few other P0s have taken priority over this, but I'll get back to it when I can!

**Comment by JCBSLMN** [comment]
having the same issue.....

**Comment by mmurph3** [comment]
@kwombach12 @teevans can we get a commitment from engineering on when this will be addressed?

**Comment by kwombach12** [comment]
@mmurph3 This is a P0 for 105. It will be resolved before we publish the release. cc: @cliffcolvin
