### ISSUE TITLE
Total Costs don't match for cluster between /overview and /cluster-inspect

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#2402]
**Describe the bug**  
When looking at the /overview page, we the total cost for a cluster under the Cluster Breakdown view does not match the total cost in cluster inspect.

**To Reproduce**  
1. Go to https://demo.kubecost.xyz/overview
2. Click on https://demo.kubecost.xyz/cluster-inspect?clusterId=kc-demo-prod&cloudId=kc-demo-prod
3. See that the total costs for last 7 days do not match. 

**Expected behavior**  
I expect to see the costs match and for cluster-inspect to specifically provide more information about the cluster.

**Screenshots**  
From /overview page:

<img width="634" alt="image" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/36980248/fc41f1d6-be0c-42f5-94c4-6131f0511910">

From /cluster-inspect:
<img width="580" alt="image" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/36980248/600717ac-03e5-4a11-b179-219caa5082a3">

**What impact will this have on your ability to get value out of Kubecost?**
It is hard to trust the numbers because the values are different for each page for the same cluster.

**Comment by mmurph3** [comment]
cc @kwombach12 @teevans @cliffcolvin

**Comment by teevans** [comment]
These numbers are calculated from different sources. One comes from Cloud Costs and one comes from allocations I believe. @aligon can confirm here though.

**Comment by mmurph3** [comment]
@teevans thanks. We've gotten feedback that this causes confusion since the numbers are different for the same cluster. Additionally, this impacts end users ability to trust and have confidence in the data being presented. 

Cc @aligon

**Comment by kwombach12** [comment]
Thanks @mmurph3 I totally agree these should match. @aligon can you provide some context on where these varying number come from? It would be strange to me if one came from Cloud Costs as I didn't think Cloud Costs had a 'cluster' filter

**Comment by nikovacevic** [comment]
Cloud Costs is the only place where we can get "unmonitored cluster" data -- because, by definition, we are not monitoring the cluster. So the CUR is the only place. But those costs aren't perfect, and will often not align with Kubecost's Assets and Allocation APIs, for various reasons. (I'm sure that @aligon used either the Assets or Allocation APIs for the cluster inspect page.)

We can certainly have a conversation about where this data should come from, and what the guarantees should be -- but I'm just not sure we can make this guarantee today.

**Comment by kwombach12** [comment]
@nikovacevic I think thats an interesting point for unmonitored clusters. I think we can be more clear in the UI, that the costs for unmonitored clusters are more approximate.

However, In the case that @mmurph3 points out, the costs aren't aligning for a monitored cluster...

**Comment by nikovacevic** [comment]
Sure, for an unmonitored cluster there is no issue with matching because there's only one story being told. For a monitored cluster, though, I'm still not certain that we'd ever expect them to line up. (We can prioritize work to that end, of course, but it's not a guarantee we make today, so this is still WAI.)

Think of it this way:  we're using labels, which are inherently imperfect, to approximately identify a CUR line item's cluster. Then we're monitoring a very specific set of things (pods, nodes, disks, load balancers, etc.). If we're monitoring something that doesn't have the right CUR label, or there are items with CUR labels that aren't being monitored by us, then we'll come up with mismatching numbers. At the end of the day, the two data sets _may_ be 1-to-1, but they may not.

This concern was raised in the development of this feature, and we proceeded under the advice to just try our best -- numbers could be approximate. So, without more work to try to figure out when and why numbers may not match, this is not a guarantee we can make.

**Comment by nikovacevic** [comment]
@avrodrigues5 We're exploring ideas for making these number match. Can you answer a few things for us on this?

1. Can you confirm that the Cluster Status API draws costs exclusively from the Cloud Costs API?
2. How hard would it be to, if status is active, draw costs from the Assets API instead? This would make the internal numbers match.

**Comment by avrodrigues5** [comment]
I dont know where the information comes in cluster inspect page but the active cluster cost is in fact drawn from asset API already

And for only unmonitored clusters from Cloud Cost Exclusively.

HEre's a screen shot of the same in my GCP cluster

![Screen Shot 2023-07-05 at 11 14 59 AM](https://github.com/kubecost/cost-analyzer-helm-chart/assets/11470561/be6ab52e-aadb-4eb7-beeb-48bc1852e711)
![Screen Shot 2023-07-05 at 11 15 25 AM](https://github.com/kubecost/cost-analyzer-helm-chart/assets/11470561/7ec88620-9059-44c8-8240-498ef613417c)

**Comment by nikovacevic** [comment]
Thank you @avrodrigues5 ! Very helpful. We're going to ask the FE team to draw the Cluster Inspect data from the Assets API so that it is guaranteed to matches.

**Comment by nealormsbee** [comment]
@jjarrett21 has merged a PR that will resolve this issue in 1.105. Closing!
