### ISSUE TITLE
Aggregation is not persisting when drilling down to container

### ISSUE THREAD

**Issue by MikeFindsThings** [kubecost/cost-analyzer-helm-chart#2413]
**Describe the bug**  
When applying an aggregation and a filter to the Allocations page, and then drilling down into a resource, the filter persists but not the aggregation.

**To Reproduce**  

1. Navigate to Monitor > Allocations
2. Aggregate by container 
3. Filter by a namespace
4. Select a container to drill down into
5. Observe that filter persists, but aggregation does not

**Expected behavior**  
Both aggregation and filters should persist

**What impact will this have on your ability to get value out of Kubecost?**
This can cause users to become confused, leading to decreased productivity and lack of trust

**Comment by kwombach12** [comment]
@MikeFindsThings I'm not sure I agree that the aggregation should persist. If I click on a specific container, and the aggregation remains container, then all I would see is a single row with the container I selected which would be an odd user experience. One alternative I could see is when a user selects a container, showing the aggregation by pod instead of namespace - would that make sense to you? I see this as a feature request given this is WAI right now.

**Comment by MikeFindsThings** [comment]
Ah yes, that makes much more sense. I said it backwards! Thanks!

**Comment by chipzoller** [comment]
Closing, stale.
