### ISSUE TITLE
No savings plans column in CUR in AWS China mainland regions break Cloud Costs

### ISSUE THREAD

**Issue by dz902** [kubecost/cost-analyzer-helm-chart#2469]
AWS China mainland regions has recently introduced Savings Plans but it seems that the columns are not in CUR yet. Monitor > Cloud Costs show nothing and in Diagnostics goes `QueryAthenaPaginated: query execution error: no query results available for query a5647fad-dae0-4232-be23-b5a80e8e3ac1`. Also there is no spot feed feature in those regions and there is an error for them too.

**Describe the solution you'd like**
Shows cloud costs without savings plans.

**Describe alternatives you've considered**
No.

**Comment by kwombach12** [comment]
@jcharcalla Can you take a look here?

**Comment by jcharcalla** [comment]
Hello @dz902

That error is typically caused by the incorrect (Athena results) s3 bucket being specified in the CloudFormation template. You should be able to find additional information about the issue in the Athena "recent queries" dashboard by searching for the query ID "a5647fad-dae0-4232-be23-b5a80e8e3ac1". You may also find additional info in the `cost-model` container logs.

We have some additional troubleshooting docs here: https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations#common-athena-errors

Spot warnings should be safe to ignore if you are not planing to use that functionality.

**Comment by dz902** [comment]
Bucket setting is correct, here is the error. The columns are not currently present in the CUR.

```
            "StateChangeReason": "COLUMN_NOT_FOUND: line 3:3: Column 'savings_plan_savings_plan_a_r_n' cannot be resolved or requester is not authorized to access requested resources",
```

**Comment by chipzoller** [comment]
Closing, stale.
