### ISSUE TITLE
[Feature] kubecost-cost-analyzer deploymentStrategy

### ISSUE THREAD

**Issue by FernandoMiguel** [kubecost/cost-analyzer-helm-chart#2593]
### Problem Statement

Currently kubecost-cost-analyzer deploymentStrategy is set to `RollingUpdate`
https://github.com/kubecost/cost-analyzer-helm-chart/blob/4ceb5ba/kubecost.yaml#L20612

When a PVC is attached, this makes it much harder for it to be freed up and reattached on another node.

OTOH prometheus is set to a much nicer option of `Recreate`
https://github.com/kubecost/cost-analyzer-helm-chart/blob/ead28a9/kubecost.yaml#L20512

Is there a specific reason for kubecost-cost-analyzer to be `RollingUpdate` or is it just a default for when no PVC is in use?

### Solution Description

use a toggle that if a PVC is in use, set `Recreate`

### Alternatives

update the docs to let partitioners know they should change this value if they use PVCs

**Comment by thomasvn** [comment]
@FernandoMiguel Thanks for the feature request! You can update Kubecost's deployment strategy via `.Values.kubecostDeployment.deploymentStrategy` ([code ref](https://github.com/kubecost/cost-analyzer-helm-chart/blob/ead28a9a2d2e0a3a926a8a350bfd5b0568c9e4f1/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L25-L28)).

Have you tried this config yet? I'm also open to changing the default to `Recreate`, since I agree that this would cause fewer issues for the new pod to attach to the PV.

**Comment by FernandoMiguel** [comment]
Before changing, I wanted to be sure it would be a recommended path.
There must be a reason why your team has it set up this way, where prometheus and analyser are set up differently.

**Comment by thomasvn** [comment]
@FernandoMiguel cost-analyzer did not need a PV at one point in time and used the `RollingUpdate` deployment strategy. At this point, I agree that setting `Recreate` as the default would allow for a better experience!

**Comment by jessegoodier** [comment]
@thomasvn 
A thought on potential startup delays in large, dynamic environments-

To me, this `recreate` idea makes sense now, because large environments should use the `query-service` (which requires federator).
  
Unless `cost-model` still pulls the same data even if `query-service` is enabled? If so, perhaps we can adjust the defaults where we only use `recreate` if `federated.primary=false`?

Small environments that have standalone kubecost would likely not have significant startup delays when recreating the PVC.

**Comment by FernandoMiguel** [comment]
FYI the pvc is not recreated in the scenario I'm describing.
Karpenter spins up a new node in the same AZ as the pvc and the attaches it to kubecost claim.
Ideally it should be a statefulset instead of deployment tho.

**Comment by sebbrandt87** [comment]
@FernandoMiguel see #2188

**Comment by FernandoMiguel** [comment]
I guess this missed again being released in 1.107.1 :|

**Comment by sebbrandt87** [comment]
no it is in @FernandoMiguel

**Comment by jessegoodier** [comment]
Good to close this then?
