### ISSUE TITLE
Bundle frontend dependencies

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#301]
Today, the Kubecost frontend requires access to external CDNs for resources. JQuery is the primary one still being used on index. Let's explore bundle as many of these as possible for users. 

Request of @gknepper, Christian

**Comment by dwbrown2** [comment]
jquery dependency now bundled. investigating other resources as a next step. 

![image](https://user-images.githubusercontent.com/298359/76013955-a5220c00-5ecd-11ea-952e-aa58cf0da15c.png)

**Comment by gknepper** [comment]
Thanks I tested and it's working, 
That's all the other missing ones:

https://code.getmdl.io/1.3.0/material.blue_grey-blue.min.css
https://fonts.googleapis.com/icon?family=Material+Icons
https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.4.4/dialog-polyfill.min.css
https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.4.4/dialog-polyfill.js
https://code.getmdl.io/1.3.0/material.min.js
https://www.googletagmanager.com/gtag/js?id=UA-129422090-1
    
I was wondering if worth the effort for you, because I don't think your customers will have a closed environments like I have here.  Thanks anyways!

**Comment by minac** [comment]
This (or another approach) will be important because Google Chrome will change the way it deals with cross-site requests:

> A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`

**Comment by minac** [comment]
Is the bundling completed? Seems like only this is outstanding:
> A cookie associated with a cross-site resource at http://gstatic.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by dwbrown2** [comment]
Yeah, still a bit more work here: 

1. Charts libraries hosted at gstatic
2. Externally hosted icons 

Hope to get to this soon, let us know if it becomes high priority!

**Comment by kirbsauce** [comment]
@dwbrown2 , not sure if this issue still exists after a year of UI enhancements, in addition to any browser modifications.  Thoughts?

**Comment by gknepper** [comment]
@kirbsauce @dwbrown2  I'm not working actively with kubecost anymore but as far as I remember all dependencies were included. Thanks for this awesome product!

**Comment by kirbsauce** [comment]
thanks for the update, @gknepper 

@minac , closing for now.  please reopen if there is still an issue.
