### ISSUE TITLE
Upgrade bundled Grafana

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#320]
Upgrading Grafana helm chart dependency should enable more datasource configuration options. Currently using v5.3.1. Latest is v6.6.2. 

Sebastian

**Comment by AjayTripathy** [comment]
A wholesale upgrade on our end for all users is likely infeasible due to the fact that labels have changed and a --force is necessary. https://github.com/kubecost/cost-analyzer-helm-chart/issues/320

Upgrading images and/or backporting new features from the helm chart is doable-- we can discuss those here or in separate issues.
