### ISSUE TITLE
Add custom athena workgroup support

### ISSUE THREAD

**Issue by korjek** [kubecost/cost-analyzer-helm-chart#897]
**What problem are you trying to solve?**
AWA Athena supports multiple workgroup configurations (with different parameters, specifically `Query result location`)
, but cost-model is uses `primary` one (which is created by default) and it's not possible to specify custom workgroup to be used by cost-model.

**Describe the solution you'd like**
That would be great if it's possible to specify athena workgroup name as a parameter for kube-cost.

**Describe alternatives you've considered**
The alternative is to stick to a default `primary` group, but we are using it already for another purpose, so we can't change `Query result location` and it will be used for kubecost as well. But this will cause that query results from different services generated to the same bucket.

**How would users interact with this feature?**
Users can specify custom athena workgroup in `values.yaml`.

**Comment by dwbrown2** [comment]
@AjayTripathy would you be able to comment? Would this be useful to add to the CloudFormation template?

**Comment by AjayTripathy** [comment]
I don't know if it makes sense to bake a workgroup other than primary into the cloudformation template,  since not all users will be setting up the CUR via cloudformation. 

We can look to support adding this to values.yaml, but @korjek just to get a sense of priority here, what's the impact of sending results from different services to the same bucket? Is there some reason that workaround wouldn't work for you for the time being?

**Comment by korjek** [comment]
@AjayTripathy no urgency here. With primary workgroup it works fine so that's only something nice to have.

**Comment by jutley** [comment]
I would like to specify a workgroup for kubecost so that I can keep its data and permissions completely separate from the rest of our Athena usage. By being forced to use the `primary` workgroup, we have to give kubecost access to any other query results using the `primary` workgroup. I think this is an important feature for information security.

**Comment by AjayTripathy** [comment]
Hi @jutley , thanks for that feedback. We'll get this prioritized and added for better data isolation.

**Comment by AjayTripathy** [comment]
We still think this is important but haven't quite gotten around to it yet. I'm attaching the help needed tag. Thanks for you patience.

**Comment by srpomeroy** [comment]
Helpful context. https://aws.amazon.com/about-aws/whats-new/2019/02/athena_workgroups/

**Comment by jhughes-mc** [comment]
This is also a problem for us. I also only found this behavior via this issue, at a minimum it should be documented that kubecost will use only the "primary" workgroup in Athena.

**Comment by AjayTripathy** [comment]
@jhughes-mc thanks for your note-- sorry you weren't able to find this issue sooner. This isn't particularly hard and we're happy to prioritize it to help your integration.

**Comment by dwbrown2** [comment]
Plan is to have in next release, v1.93!

**Comment by dwbrown2** [comment]
PRs out and merged in case any one is interested in giving feedback! 

https://github.com/kubecost/cost-model/pull/1175
https://github.com/kubecost/cost-analyzer-helm-chart/pull/1386

Big shout out to @dramich for having this ready before this coming release.
